### ISSUE TITLE
致命错误

### ISSUE THREAD

**Issue by GGYNGG7** [XndroidDev/Xndroid#1]
start fqrouter fail: fai led to
list /proc/self/fd
这是咋了

**Comment by lisuke** [comment]
一样是这个问题

**Comment by lisuke** [comment]
刚刚在手机里打开终端测试了一下, 
`ls /proc/self/fd`
result:  
`0 1 2 3`

**Comment by GGYNGG7** [comment]
@lisuke 我不打算搞安卓xx-net 了，速度卡一点的vpn够用了

**Comment by GGYNGG7** [comment]
身心俱疲

**Comment by XndroidDev** [comment]
现在兼容性还有问题,得多找点手机测试

**Comment by XndroidDev** [comment]
@GGYNGG7  @lisuke  
"failed to list /proc/self/fd" 已修复,重新下载最新版安装:
[https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-release.apk](https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-release.apk)
