### ISSUE TITLE
Android 8 致命错误

### ISSUE THREAD

**Issue by Scorpio201712** [XndroidDev/Xndroid#10]
oneplus 1+3t 
os: Android 8 

致命错误，fqrouter 意外退出。

![screenshot_20171204-123224](https://user-images.githubusercontent.com/17558215/33536834-7ec40472-d8f2-11e7-994d-13669c6d9b13.jpg)

**Comment by XndroidDev** [comment]
@Scorpio201712 
将日志发过来

**Comment by Scorpio201712** [comment]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1525869/xndroid-logs.tar.gz)

谢谢！

**Comment by XndroidDev** [comment]
@Scorpio201712 
在Android O 使用busybox的ln tar chmod 命令使 都出现 “Bad system call”
我这里没有Android O 的手机来测试，如果可以的话你试试最新版的busybox上述命令能否正常使用

**Comment by XndroidDev** [comment]
http://developers.googleblog.cn/2017/07/android-o-seccomp.html

**Comment by Scorpio201712** [comment]
Busybox 安装后运行提示需要root权限只能退出，然后安装termux，可以运行上述几个命令，但是fqrouter还是出现致命错误，无法运行。

**Comment by XndroidDev** [comment]
@Scorpio201712  你留一下邮箱，我将测试版本发给你

**Comment by scljy** [comment]
scljy@qq.com

**Comment by XndroidDev** [comment]
@Scorpio201712  
卸载原有版本后,安装这个,可能仍然无法正常使用.不管是否正常,都将导出的日志和/sdcard/xndroid_test.log 发过来​
https://drive.google.com/open?id=1O6aMpsvwrEOElEP0cPbWRcRgZrkg4YYH

**Comment by scljy** [comment]
@XndroidDev 依然是这个错误，日志已发邮箱。

**Comment by XndroidDev** [comment]
@scljy  @Scorpio201712 
麻烦重新测试一下这个,同样将日志发过来
https://drive.google.com/open?id=0B_hfxE3IgdTeMEhUa3dRejNTbHNJUWxSZkNZc19La1VpeG1j

**Comment by scljy** [comment]
APPid 设置后仍显示（未设置AppID,讯问受限）
导入证书依然？
teredo状态：offline
NAT类型：unkown
teredo地址：none

**Comment by 785045633** [comment]
一加3 8.0可以用了感谢！@XndroidDev ，有个问题就是Google play和Google全家桶APP连不上，浏览器可以，请问还需要设置什么吗

**Comment by scljy** [comment]
浏览器换成chrome，通过可以进youtube\google\facebook，但很慢，app不能用 @XndroidDev

**Comment by XndroidDev** [comment]
访问速度主要取决于网络环境,由XX-Net决定.很多国外APP由于证书问题,确实无法正常使用.
另外你重新下载一下最新版本,测试版本启动时的测试比较耗时. https://raw.githubusercontent.com/XndroidDev/Xndroid/master/update/app-release.apk

**Comment by iikk** [comment]
国外APP由于证书问题,确实无法正常使用.
除了root还有其他办法搞定这个问题吗，只能浏览器翻墙不够方便

**Comment by XndroidDev** [comment]
@iikk  其实对于这些APP即使root了, 安装为系统证书,也是不接受GAE的证书.  不过对于Android 7.0
以上的手机默认不信任用户证书还是有帮助的

要彻底解决这些APP的证书问题, 唯一可行的办法是 , 尝试借助xposed, 看能否强制让应用信任用户证书和系统证书
