### ISSUE TITLE
安装之后，一个ip都搜索不到

### ISSUE THREAD

**Issue by no-name2017** [XndroidDev/Xndroid#101]
所有版本都试过了，都是一个ip都搜索不到

**Comment by AnyWAT** [comment]
安卓4.4.2，xndroid1.1.9，XX-Net3.10.4已退回到3.8.4（没有智能路由的最高版本），xndroid首页关闭“自动扫描线程”，最大扫描线程数50（如不能维持稳定就再增大：IP延时偏小且基本不变，有效IP数趋近IP总数上限自定义500），仅IPv6：一切正常，你可自由访问互联网😂
xndroid中断后重开，最好在启动后立马手动扫描IP
以上几乎等同PC“臭大街法则”😜

**Comment by AnyWAT** [comment]
手动管理——全部已发布版本——想用哪个选哪个，下载后会自动安装

**Comment by no-name2017** [comment]
@AnyWAT 大佬，是下载那个zip的压缩文件吗？点击了没反应，也没有下载噢

**Comment by AnyWAT** [comment]
首先得代理正常，此站上图、下载需代理

**Comment by no-name2017** [comment]
我试过了，并不是代理的问题，不知道为什么就是不开始下载

**Comment by AnyWAT** [comment]
再说版本不是重点，稳定版1.1.9 (XX 3.10.4)👍

**Comment by no-name2017** [comment]
大佬，我投降了，搞不定

**Comment by AnyWAT** [comment]
不会你手机上有某些国祸吧？

**Comment by XndroidDev** [comment]
1. 建议使用最新版
2. 建议XX-Net更新到最新
3. 尝试不同的网络环境
4. 封锁太严重, 仍然无法使用, 则建议使用其它工具

**Comment by no-name2017** [comment]
@AnyWAT  手机很干净啊，其他翻墙软件都正常。

@XndroidDev  不是封锁严重，电脑版的xx-net一切正常，到了手机就不正常，想把xx-net的版本切换回到老版本，不知道如何操作。

**Comment by AnyWAT** [comment]
不是卸载、清理再安装？

**Comment by XndroidDev** [comment]
@no-name2017  teredo状态如何, Xndroid, XX-Net 具体版本?

**Comment by SeaHOH** [comment]
手机用的是 wifi 和电脑一个内网？

**Comment by XndroidDev** [comment]
@no-name2017  建议XX-Net 3.11.7版及以上, Xndroid1.1.10 内置 XX-Net 3.11.7

**Comment by AnyWAT** [comment]
从一（3.10.4👍）而终者表示不服🤣

**Comment by XndroidDev** [comment]
@no-name2017  怀疑是你系统的ipv6支持的bug
https://github.com/XndroidDev/Xndroid/issues/23

**Comment by no-name2017** [comment]
各位大佬，不好意思，周末没上网，刚看到各位大佬回复，抱歉。
@SeaHOH  是的，手机和电脑都是同一个内网。电脑的xx-net 3.11.10 运行正常，xndroid 1.1.10里的3.11.10扫描不到ip。
@XndroidDev  我忘记跟大佬你说了，我前两晚xndroid能搜索到几个IPv4，也能翻，所以teredo没问题，现在的问题是扫描不到ip，这就很奇怪了，电脑正常，手机就一个ip也没扫到，搞不懂是什么原因。

**Comment by no-name2017** [comment]
不折腾啦，用ss好了，谢谢各位大佬帮忙！
