### ISSUE TITLE
请教内嵌的xxnet升级了，本软件没升级，怎么给xxnet升级？

### ISSUE THREAD

**Issue by hongkonghot** [XndroidDev/Xndroid#102]
请教内嵌的xxnet升级了，本软件没升级，怎么给xxnet升级？

**Comment by AnyWAT** [comment]
https://github.com/XndroidDev/Xndroid/issues/93

**Comment by hongkonghot** [comment]
检查更新，提示 获取最新版本失败！怎么解决啊！
