### ISSUE TITLE
非常感謝開發者

### ISSUE THREAD

**Issue by caofengzi** [XndroidDev/Xndroid#104]
感謝作者無私的付出，新版本已經解決了正常退出需要手動停止vpn的bug，謝謝。

**Comment by XndroidDev** [comment]
我还没有针对这个问题进行修改。
你是从哪个版本更新到哪个版本，可能是因为换成了debug版，SDK行为不一样

**Comment by caofengzi** [comment]
就是更新到debug版了。謝謝
