### ISSUE TITLE
ip6不可用，1.1.10版仍然提示原生ip6可用并禁用teredo

### ISSUE THREAD

**Issue by Kidagakash** [XndroidDev/Xndroid#109]
三星c8，安卓7.1，xndroid1.1.10。
无ip6的网络，wlan和4g下依然提示原生ip6可用，禁用teredo。导致上不了网。
xx-net3.1.10提示ip6不可用。

**Comment by sbitoh** [comment]
我也是这个问题 请问怎么禁用原生ipv6

**Comment by sbitoh** [comment]
就是楼上说的这个意思

**Comment by Kidagakash** [comment]
Help?

**Comment by XndroidDev** [comment]
可能有某个网络接口分配了本地的ipv6地址，没有被排除

请上传日志
@Kidagakash @sbitoh

**Comment by XndroidDev** [comment]
出现此问题后，点击菜单中的`导出日志`

**Comment by Kidagakash** [comment]
好的

**Comment by Kidagakash** [comment]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2046786/xndroid-logs.tar.gz)

**Comment by Kidagakash** [comment]
上传日志了

**Comment by XndroidDev** [comment]
@Kidagakash
3: rmnet1: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1300 qdisc mq state UNKNOWN
qlen 1000
    link/ether 82:1d:b3:ff:e3:de brd ff:ff:ff:ff:ff:ff
    inet6 2409:8803:8380:74fe:66cd:ab6:d18f:e5c4/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::66cd:ab6:d18f:e5c4/64 scope link
       valid_lft forever preferred_lft forever

移动网络中确实分配到了原生的ipv6地址，在4G网络下判断没有问题，
至于上不了国外网站，可能是手机系统BUG，系统没有添加ipv6路由项；
或者是中国移动仅分配了ipv6地址，但没有提供可用的ipv6网络。


在连wifi时，手机没有释放掉移动网络的ip/ipv6地址，导致仍然认为有原生ipv6

% [whois.apnic.net]
% Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html

% Information related to '2409:8000::/20'

% Abuse contact for '2409:8000::/20' is 'abuse@chinamobile.com'

inet6num:       2409:8000::/20
netname:        CMNET-V6-20110823
descr:          China Mobile Communications Corporation
descr:          Mobile Communications Network Operator in China
descr:          Internet Service Provider in China
country:        CN

**Comment by XndroidDev** [comment]
@Kidagakash

移动网络下，在终端（如Termux, adb shell）中执行命令"ping6 2001:13d2:2801::11", 看输出提示是什么

**Comment by XndroidDev** [comment]
还有顺带看看“ip route get 2001:13d2:2801::11”命令的输出结果

**Comment by Kidagakash** [comment]
移动4G，Termux。
输：ping6 2001:13d2:2801::11
提示：connect:network is unreachable
————————————————————
输：ip route get 2001:13d2:2801::11。
提示：unreachable 2001:13d2:2801::11 from :: as to :: dev lo  proto kernel  src 2409:8803:8232:7989:b3eb:9cec:2394:1c8d  metric 4294967295  error -101

**Comment by XndroidDev** [comment]
大概系统的路由表有问题

**Comment by XndroidDev** [comment]
已修复，但编译有点问题，过两天更新

**Comment by Kidagakash** [comment]
作者棒棒滴。

**Comment by XndroidDev** [comment]
请下载安装测试
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

**Comment by XndroidDev** [comment]
已修改，请下载安装测试
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

**Comment by Kidagakash** [comment]
试试，多谢

**Comment by XndroidDev** [comment]
close后可继续回复
