### ISSUE TITLE
android 8 致命错误 等待fqroute响应超时

### ISSUE THREAD

**Issue by scljy** [XndroidDev/Xndroid#11]
android 8 致命错误 等待fqroute响应超时

**Comment by scljy** [comment]
android 8 致命错误 fqroute意外退出

**Comment by XndroidDev** [comment]
以收到反馈：
https://github.com/XndroidDev/Xndroid/issues/10
Android 8.0 运行busybox的一些命令会 system call error, 但我这里没有Android 8.0的手机来测试，具体情况不清楚。有条件的话，里可以试一试最新版busybox的 tar，ln，chmod 命令是否可用

**Comment by scljy** [comment]
好的

**Comment by XndroidDev** [comment]
@scljy 你也可以安装termux,里面会自带busybox,看看上述命令是否可用

**Comment by scljy** [comment]
可以执行

**Comment by scljy** [comment]
安装termux后，可以运行上面几个命令，下一步该怎么处理？

**Comment by XndroidDev** [comment]
@scljy  等会我发一个测试版本，你试一下

**Comment by XndroidDev** [comment]
@scljy  你留一下邮箱，我将测试版本发给你

**Comment by XndroidDev** [comment]
此问题统一在  https://github.com/XndroidDev/Xndroid/issues/10  讨论
