### ISSUE TITLE
无限启动中，一直是初始化转圈

### ISSUE THREAD

**Issue by HeiLAAS** [XndroidDev/Xndroid#115]
root之前完全没问题，只是不能导入系统证书，root之后就出现了这个问题
设备:zx1c 8.0

**Comment by XndroidDev** [comment]
应该是在等待授权工具授权. 你打开授权工具(如SuperSU)管理界面,同意授权再试试

**Comment by HeiLAAS** [comment]
解决了，谢谢！

**Comment by cyh19910216** [comment]
非常抱歉回复了这个老帖子，但是我出现了同样的问题
root授权工具是最新的magisk 20.2，软件版本1.3.1

在magisk里删除授权后，以VPN模式可以打开
但是一旦给予root权限，就会无限初始化转圈圈

已做过尝试：重刷magisk；重装软件；删除root权限后重新授权
全部失败

手机：小米max3，MIUI 11，Android 9
