### ISSUE TITLE
1.2.0致命错误

### ISSUE THREAD

**Issue by klcb2010** [XndroidDev/Xndroid#117]
更新后，弹出致命错误   清除数据也不能解决问题

**Comment by XndroidDev** [comment]
请上传日志

**Comment by klcb2010** [comment]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2110581/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
gz校验错误
重新下载安装
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk
