### ISSUE TITLE
提示 【致命错误】xx-net意外退出，麻烦看下日志，谢谢了啊！

### ISSUE THREAD

**Issue by qidanei624** [XndroidDev/Xndroid#118]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2113714/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
你的机型和系统版本?
转到 https://github.com/XndroidDev/Xndroid/issues/53

**Comment by qidanei624** [comment]
三星 安卓4.1.2版本的
