### ISSUE TITLE
系统支持原生ipv6，禁用terado，导致无法使用！

### ISSUE THREAD

**Issue by Anway2** [XndroidDev/Xndroid#119]
最近换了nubia Z17，刷了Resurrection Remix 5.8.5（基于7.1.2），安装xndroid，提示”系统支持原生ipv6，禁用teredo“（大概是这意思）。然后扫描ip数一直为0，无法使用！
之前我一直在另一部安卓7.1.2的系统中使用正常的（版本号都是3.11.7）。
想问一下大神：我需要如何操作或设定才能让xndroid用起来？谢谢！

**Comment by XndroidDev** [comment]
安装最新版:
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

如果仍然有问题, 在`菜单`-`选择启动组件`中,取消勾选`ipv6可用时禁用teredo`

**Comment by Anway2** [comment]
安装新版后未做任何设置，顺利FQ!
感谢！
