### ISSUE TITLE
请教一些问题，谢谢

### ISSUE THREAD

**Issue by theratlesnake** [XndroidDev/Xndroid#12]
1，好像在app里找不到隧道的设置入口，如果要自己更换Teredo服务器，该怎么操作呢？
2，如果xx-net要自己手动设置一些配置（manual.ini），手机没root，找不到程序的安装目录，该怎么办？
3，安卓6以下的手机可以运行吗？

很感谢大神贡献的那么好的作品，以前xx-net运行后，面板经常会看不到某些数据，而你的则完美的运行，非常好的作品，感谢感谢。

**Comment by XndroidDev** [comment]
目前不支持更换teredo服务器,暂不支持无root手动修改配置文件,不过默认配置是按最大权限,一般不需修改,后续会考虑手动修改的可能性.支持安卓6以下,android 8.0 正在想办法解决

**Comment by theratlesnake** [comment]
好的，非常感谢大神的解答，期待做得越来越好！
