### ISSUE TITLE
扫描不到IP，无足够IP可用

### ISSUE THREAD

**Issue by dongyanyy** [XndroidDev/Xndroid#121]
更新了1.2之后，IP数量为0,IP延迟9999，坚果pro2，安卓基带7.11,XX-NET 3.10.4

**Comment by XndroidDev** [comment]
手动更新一下XX-Net

**Comment by AnyWAT** [comment]
@dongyanyy https://github.com/XndroidDev/Xndroid/issues/101 2楼

**Comment by dongyanyy** [comment]
更新了，我再试试

**Comment by ffdzpilot** [comment]
更新到新版可用ip也是不足，3个2个1个，是不是和某生日有关啊！

**Comment by XndroidDev** [comment]
将XX-Net更新到了最新版(3.12.+)吗?

**Comment by dongyanyy** [comment]
更新了，还是不行，不过我PC端正常，用PC端也行

**Comment by ffdzpilot** [comment]
我整明白了，我只更新了xndroid，不知道xx-net还需要离线升级，这次终于好了，ip也有了，谢谢！

**Comment by jxyk2007** [comment]
> 更新到新版可用ip也是不足，3个2个1个，是不是和某生日有关啊！

1.更新xxnet 。2.重启手机 。3.ok

**Comment by jxyk2007** [comment]
![_20181028193305](https://user-images.githubusercontent.com/44092526/47615324-62397280-dae8-11e8-85c1-7d6054974cb8.jpg)
![Uploading 微信图片_20181028193253.jpg…]()

**Comment by jxyk2007** [comment]
![_20181028193253](https://user-images.githubusercontent.com/44092526/47615331-7d0be700-dae8-11e8-848a-0f79289dede6.jpg)
