### ISSUE TITLE
这样设置以后依旧无法通过电脑代理访问外网

### ISSUE THREAD

**Issue by subtank** [XndroidDev/Xndroid#122]
![screenshot_20180624-102048](https://user-images.githubusercontent.com/19743209/41815270-65146478-7798-11e8-80c0-e47afb0ebbe4.png)

**Comment by AnyWAT** [comment]
sock5 ？http ？8086 or 8087

**Comment by subtank** [comment]
怎样修改X_Tunnel的监听呢？我测试了8087可用，但是我那个游戏不支持gae代理
