### ISSUE TITLE
可以上谷歌，谷歌应用商店不能用

### ISSUE THREAD

**Issue by wqbear** [XndroidDev/Xndroid#123]
1.2.0版，XX-Net更新到3.12.3，私有ID
谷歌能正常上，应用商店进去显示“从服务器检索信息时出错”。
手机上谷歌账户不能登录，显示无法连接到互联网。
怎么操作才能正常使用谷歌应用商店？
mate 10 Android 8.0

**Comment by wqbear** [comment]
XX-Net Status:

sys-platform: armv7l, Linux-4.4.23+-armv7l-with-libc
os-system: Linux
os-version: #1 SMP PREEMPT Wed May 9 03:05:37 CST 2018
os-release: 4.4.23+
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 8.0.0; ALP-AL00 Build/HUAWEIALP-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36
xxnet-version: 3.12.3
python-version: 2.7.2
openssl-version: 16.2.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:134 ipv4:0 ipv6:128
ipv4-status: OK
ipv6-status: OK
connected-link: new:1
worker: h1:9 h2:0
scan-ip-thread-num: 12
ip-quality: 600
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by SeaHOH** [comment]
等会儿会发修复版本

**Comment by steclukist** [comment]
xxnet升级到了3.12.4，xndroid升到最新的测试版，还是跟lz遇到一样的问题。
手机上的浏览器可以登录myaccount.google.com

**Comment by SeaHOH** [comment]
3.12.4 没有用吗，已经一年多不折腾手机了，等 @XndroidDev 来验证下。

**Comment by XndroidDev** [comment]
浏览器能否访问 play.google.com

请仔细查看 https://github.com/XndroidDev/Xndroid/issues/14 以及 https://github.com/XndroidDev/Xndroid/blob/master/README.md#兼容性与局限性

**Comment by XndroidDev** [comment]
https://github.com/XX-net/XX-Net/issues/9719

**Comment by wqbear** [comment]
mate 10 Android 8.0 手机没有ROOT
手机原生带谷歌套件
浏览器可以访问 play.google.com
有没有什么办法能突破 证书 的 兼容性与局限性 ？

**Comment by AnyWAT** [comment]
👀 #14 使用手机XX-Net 的X-tunnel 或使用电脑XX-Net 的8087代理分享？
