### ISSUE TITLE
可以打包个去除证书警告闪电浏览器吗？

### ISSUE THREAD

**Issue by catcherxuefeng** [XndroidDev/Xndroid#124]
集成LightningBrowser 4.5.1, 默认使用 localhost:8087 代理, 关闭证书警告
我是使用xxnet http 代理进行手机上网的

**Comment by XndroidDev** [comment]
这个是用来干什么

**Comment by AnyWAT** [comment]
anthonycr/Lightning-Browser: A lightweight Android browser with modern navigation https://github.com/anthonycr/Lightning-Browser

**Comment by XndroidDev** [comment]
不警告证书错误的浏览器已经有了一些, 如:X浏览器,Via 等. 另外部分浏览器还可以选择忽略错误, 如小米浏览器. 因此没有必要单独编译.

**Comment by catcherxuefeng** [comment]
好的，我去下载试试，感谢回答
