### ISSUE TITLE
Xndroid退出后只能通过手机重启才能实现正常上网

### ISSUE THREAD

**Issue by fredericky123** [XndroidDev/Xndroid#126]
8.0系统，这是为何？每次用后要重启手机好麻烦，求解答。

**Comment by XndroidDev** [comment]
ROOT模式还是VPN模式? 上传一下日志

**Comment by fredericky123** [comment]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2161888/xndroid-logs.tar.gz)
@XndroidDev 非常感谢！

**Comment by fredericky123** [comment]
另外，手机提示“网络可能会受到监控”，这个提示能去除吗

**Comment by XndroidDev** [comment]
你用的vpn模式，没道理退出后会影响手机网络。你看看退出后通知栏vpn的通知是否还存在，存在的话手动断开。
如果vpn的通知退出后没有了但仍然无法访问网络的话，可能是是手机系统的bug，你看看其他使用vpn服务的应用(如 蓝灯 赛风 ss)退出后是否正常

**Comment by XndroidDev** [comment]
"网络可能会受到监控"，清楚用户凭证(证书)就没有了。
你有两个选择: 将手机root，导入为系统证书；不导入证书，只在可忽略证书错误的浏览器中使用

**Comment by fredericky123** [comment]
@XndroidDev 退出后没有vpn的提示了，使用其他vpn如lantern等不会出现这个错误，应该不是系统的原因吧 只有xndroid不正常

**Comment by xiaoteai** [comment]
XX-Net Status:

sys-platform: aarch64, Linux-3.10.72+-aarch64-with-libc
os-system: Linux
os-version: #1 SMP PREEMPT Sat Feb 24 06:59:06 CST 2018
os-release: 3.10.72+
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 5.1; OPPO R9m Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36
xxnet-version: 3.7.16
python-version: 2.7.2
openssl-version: 0.14 TLSv1_2 h2:no
ipv6-tunnel: Developing
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 190
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: true

**Comment by XndroidDev** [comment]
已发现此问题, 最近比较忙, 有时间再解决. 问题是VpnService运行在单独的进程里, 且调用stopService在部分手机上不起作用. 目前可以手动在vpn设置里头点击断开连接.

**Comment by fredericky123** [comment]
@XndroidDev 手动无法断开连接唉 如果取消开启vpn 会自动跳转到Xdroind界面 依旧无法成功推出

**Comment by XndroidDev** [comment]
可尝试在"设置"-"更多应用"中强行终止应用的所有进程

**Comment by XndroidDev** [comment]
更新到最新版
https://github.com/XndroidDev/Xndroid/releases/download/1.2.4/app-release.apk

**Comment by fredericky123** [comment]
亲测已解决 赞
