### ISSUE TITLE
安卓8.0 小米6 致命错误——XX-NET 意外退出

### ISSUE THREAD

**Issue by gxy17886** [XndroidDev/Xndroid#127]
1.小米6,安卓8.0，MIUI10，Xndroid 1.2和1.1.10都试过了，已给root，一打开app等待一会后就出现 致命错误——XX-NET 意外退出，过十几秒变成 等待XXNET响应超时（VPN模式也一样）（我在电脑模拟器上运行就可以打开）

[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2159493/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
请卸载后重新下载安装
https://github.com/XndroidDev/Xndroid/releases/download/1.2.2/app-release.apk

**Comment by Weijee** [comment]
1.2.3又出现
