### ISSUE TITLE
能否把teredo功能单独提取出来，做个app

### ISSUE THREAD

**Issue by iopxiang** [XndroidDev/Xndroid#13]
这样就能通过ipv6 hosts 来翻墙了

**Comment by XndroidDev** [comment]
teredo 是基于fqrouter实现的,单独拿出来用处也不大

**Comment by chendaihang** [comment]
@XndroidDev  teredo.py 感觉很强大能否替代windows自带的和linux下的miredo的功能集成到xx-net中

**Comment by XndroidDev** [comment]
可以代替linux下的miredo， 需要先配置tun， ipv6地址路由，
 置于windows， 不清楚它的tun怎么弄， 高手可以尝试

**Comment by xxnet** [comment]
​Windows 也有可能，只是需要参考开源项目，重新实现一遍。
另一个思路是，Python 和teredo 服务器进行UDP通讯，转化为Socks代理使用，就避免了和操作系统绑定。
难点在于IP层和TCP层，要实现一个TCP 协议，效率是个问题，稳定性、兼容性会是最大问题，TCP协议很复杂。

https://jvns.ca/blog/2014/08/12/what-happens-if-you-write-a-tcp-stack-in-python/
https://github.com/jvns/teeceepee

**Comment by googlehim** [comment]
单独做一个Android版的teredo来支持ipv6还是蛮有需求的，支持ipv6后可以选择通过ipv6地址来访问自己的搭的服务器，比如ss客户端是支持ipv6的，但手机上没有teredo，用不了ipv6地址。

**Comment by wooowooo** [comment]
有现成的https://github.com/yingted/MireDroid
