### ISSUE TITLE
除浏览器外，其他APP均连不上网

### ISSUE THREAD

**Issue by xiaohuaihuaihuai** [XndroidDev/Xndroid#130]
1.提交问题前先查看主页readme中是否有描述相关问题
2.再查看issue板块中是否已经提交过相关问题, 有的话就在此issue中提交问题
3.仍然没有相关描述再创建issue, 注意反馈: 手机型号, 系统版本, Xndroid版本, XX-Net版本, 异常提示. 如果有自动导出日志则附上日志, 如果没有自动导出日志, 则重试出现问题时的操作,再次出现问题后点击菜单中的导出日志. 注意上传整个'xndroid-logs.tar.gz', 如果无法上传,则发送到xndroiddev@gmail.com,并附上上述相关信息.
4.日志和相关信息不要保存在国内网站上. 日志尽量传到issue中, 方便后续查看, 实在无法上传则通过邮箱发送.

**Comment by AnyWAT** [comment]
https://github.com/XndroidDev/Xndroid
![default](https://user-images.githubusercontent.com/37962734/42498579-1d9ff390-845f-11e8-9f86-d2c4913c9846.png)

**Comment by xiaohuaihuaihuai** [comment]
是不是手机不root,就不能导入为系统证书啊

**Comment by AnyWAT** [comment]
貌似94

**Comment by AnyWAT** [comment]
共享（电脑XX-Net ）代理网络，也可解决其他APP如，YouTube、Google play

**Comment by xiaohuaihuaihuai** [comment]
好的   谢谢啦
