### ISSUE TITLE
手机上使用耗电量有点大，发热严重。。。

### ISSUE THREAD

**Issue by GLingDroid** [XndroidDev/Xndroid#131]
应该跟持续使用特别是移动网络时有关，
就是一直在发送接收数据包。
现在xxnet部分在逐渐增多可设置选项，gae部分最佳的就是“能动则动，能静则静”，就是只有在有数据请求时才开动gae。
照理说隧道出去后ip应该死得不太快吧，主要是隧道这边需要维持怎样一个live状态。
怀念g0pr0xy那种静如处子动如脱兔的感觉，用起来手机一点不热，耗电量很少。

手机上耗电量最大的是cpu长时间高负载和长时间发送接收数据包，即使数据包很小。
所以策略就是短时间扫描优于始终/长时间扫描，优先使用缓存的上次可用ip。

外行人随便说说想法，代码方面就无能为力了，只有测测参数组合还行。

**Comment by XndroidDev** [comment]
你可以测试一下在启动设置里关闭xxnet，对比和开启xxnet的耗电量。可能耗电量差别不大

**Comment by SeaHOH** [comment]
由于 IPv6 隧道质量越来越差，IP 扫描后续修改没法顾虑到移动网络使用，只能关闭自动调整线程才不会一直进行扫描。

**Comment by GLingDroid** [comment]
Xndroid 1.2.2+xxnet 3.12.10发热情况大为改善，xxnet 3.12.10设置了“被动”，“自动扫描”关闭和扫描线程“0”。
但是不太明白这些设置的优先情况，
比如重新进入xxnet设置页后，“提交设置级别”是关闭状态，“自动扫描”又被打开了，扫描线程有时会是6或者10，
也就是说我设置了关闭自动扫描，扫描线程为0后，后退再进入这些页面发现没用。。。
当然，实际使用上是有改善的，手机终于凉了，
在浏览非被墙网页时，在3～5分钟每1%电量，主要看后台有没有在扫描，比如状态栏网速监测显示0的时间较长则能到5分钟，
作为比较同等状态关闭Xndroid，是7分钟。

主要还是扫描线程设置0不起作用，后台还是在扫。

**Comment by SeaHOH** [comment]
`设置级别`是几个设置的集合，按激烈程度大概分了几个档次，选中`提交设置级别`才能提交设置，提交完成就会重置按钮状态。
`设置级别`中的`自动扫描`和`扫描线程`始终是打开的，需要设置后才能再次关闭。

还是建议根据使用情况由 Xndroid 来控制部分关键参数。 @XndroidDev

**Comment by AnyWAT** [comment]
“自动扫描”又被打开了——程序首页（Xndroid）也有“自动扫描线程”开关，下页（XX-Net）高级，原本就有“自动调整扫描线程数”开关
