### ISSUE TITLE
谁能告诉我这玩意儿究竟怎么用，没个教程啊

### ISSUE THREAD

**Issue by oushii** [XndroidDev/Xndroid#141]
1.提交问题前先查看主页readme中是否有描述相关问题
2.再查看issue板块中是否已经提交过相关问题, 有的话就在此issue中提交问题
3.仍然没有相关描述再创建issue, 注意反馈: 手机型号, 系统版本, Xndroid版本, XX-Net版本, 异常提示. 如果有自动导出日志则附上日志, 如果没有自动导出日志, 则重试出现问题时的操作,再次出现问题后点击菜单中的导出日志. 注意上传整个'xndroid-logs.tar.gz', 如果无法上传,则发送到xndroiddev@gmail.com,并附上上述相关信息.
4.日志和相关信息不要保存在国内网站上. 日志尽量传到issue中, 方便后续查看, 实在无法上传则通过邮箱发送.

**Comment by oushii** [comment]
XX-Net Status:

sys-platform: armv7l, Linux-4.4.23+-armv7l-with-libc
os-system: Linux
os-version: #1 SMP PREEMPT Thu May 31 19:28:43 CST 2018
os-release: 4.4.23+
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 8.0.0; STF-AL00 Build/HUAWEISTF-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36
xxnet-version: 3.12.9
python-version: 2.7.2
openssl-version: 16.2.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: auto
gws-ip-num: total:0 ipv4:0 ipv6:0
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 200
ip-quality: 9999
is-idle: 0
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by XndroidDev** [comment]
teredo隧道不稳定或手机系统ipv6支持的bug
