### ISSUE TITLE
除了浏览器可以翻墙，其他客户端均不可翻墙，ins\twitter\facebook\play....

### ISSUE THREAD

**Issue by YuenJoshua** [XndroidDev/Xndroid#142]

**Comment by zentst** [comment]
我已经放弃了，8.1安卓，看说明是证书方面有局限性，root导入系统证书就可以。然后就root了，发现完全没用。估计要7才可以吧。

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/14
