### ISSUE TITLE
除了浏览器能翻墙之外，怎样才能使用其他软件翻墙？

### ISSUE THREAD

**Issue by zongdream** [XndroidDev/Xndroid#146]
安装了，能使用，但只能用浏览器翻墙，其他的软件如何使用翻墙？

google play、Ins、facebook、twitter...都用不了.....

**Comment by hnmrxz** [comment]
android 8.0同样问题，另外打开APP可以连接，但点XX-NET或者fqroute有时经常崩溃

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/14
