### ISSUE TITLE
Xndroid安卓8.0启动崩溃，版本1.2.2

### ISSUE THREAD

**Issue by shineyik** [XndroidDev/Xndroid#148]
Xndroid安卓8.0启动崩溃，尝试过几个版本都是同样的问题。 
![screenshot_20180728-154145](https://user-images.githubusercontent.com/22080729/43354499-27ed1c7c-9280-11e8-8e5b-31bcfd1806ce.png)
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2237775/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
手机机型? 系统版本? 这个是调用证书安装器. 其他Android 8.0的手机都没有问题, 可能你手机的证书安装器被阉割了. 下个版本会把这个异常把这个异常给catch住, 但就需要手动安装证书了.
