### ISSUE TITLE
不能全局代理

### ISSUE THREAD

**Issue by Mickiman** [XndroidDev/Xndroid#150]
最新debug版本，手机是samsung s7e，android8.0，chrome可以正常使用，但是play商店，youtube客户端就不可以

**Comment by stonyz** [comment]
因为某些app不支持GAE的证书，作者说过了。 
尝试关闭 XX-NET,  就会走teredo的通道，就可以。 因此证明全局代理本身是没有问题，问题是在证书上吗

**Comment by Mickiman** [comment]
请教一下，禁用xx-net后是要走自己的代理吗?禁用后不能翻出去了。是不是说用这个gae证书就没有办法使用这些app了?

**Comment by stonyz** [comment]
1. 我禁用xx-net后，还可以翻墙，我觉得可能是走的teredo
2. 可以增加自己的代理,比如ss,没有证书的问题。

@XndroidDev 解释一下？可能我理解的不对

**Comment by XndroidDev** [comment]
1 可能你那边网络环境比较好，禁用teredo后可ipv6直连
2 禁用后可使用ss等个人代理

**Comment by AnyWAT** [comment]
禁用（ipv6隧道）teredo后可（原生）ipv6直连
