### ISSUE TITLE
能增加分应用代理和全局代理功能吗？

### ISSUE THREAD

**Issue by koolwiki** [XndroidDev/Xndroid#154]
谢谢大神开发这么好的软件！现在很多代理软件（如：shadowsocks和v2ray）都可以分应用代理，请问大神能增加这个功能吗？此外，有时候直联某些网站（如github）很慢，也想通过代理进行访问，而当前的版本好像没法操作。请问能增加全局代理的功能吗？谢谢！

**Comment by AnyWAT** [comment]
Root 了？ 修改 data\launcher\config.yaml 
proxy: disable（/pac/smart_router/x_tunnel/gae）
如同Win 系统底部托盘的几个（全局控制）代理？

**Comment by koolwiki** [comment]
手机没有root

**Comment by XndroidDev** [comment]
这个好象是Android N/O 的特性, 以后再考虑

**Comment by AnyWAT** [comment]
安卓XX-Net（系统代理：或GAE、或PAC、或Smart_Router、或X_Tunnel）代理正常，有代理设置的App 设置自身代理后正常，没有代理设置的App 如Chrome 却无法打开 https://t.co/WdwQLicaek “未发送任何数据(ERR_EMPTY_RESPONSE)”， 即安卓XX-Net 系统全局代理工作不正常？

**Comment by XndroidDev** [comment]
已添加此功能, 请更新到最新版

https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

**Comment by koolwiki** [comment]
@XndroidDev 已经更新成功，非常感谢！
