### ISSUE TITLE
显示已连接,但是不能上网是为什么

### ISSUE THREAD

**Issue by luziming** [XndroidDev/Xndroid#157]
最新版本,提示一切正常,但是不能上网,1加5t ,8.0

**Comment by AnyWAT** [comment]
检查此刻的有效IP、IP延时及连接池，点击“检查IP”，完成后对比下前述3项：或许代理已正常？

**Comment by XndroidDev** [comment]
把XX-Net状态信息, teredo状态, fqrouter代理列表  贴上来

**Comment by XndroidDev** [comment]
没有足够信息, 无法判断
