### ISSUE TITLE
X-Tunnel密码遗忘

### ISSUE THREAD

**Issue by Chen9833** [XndroidDev/Xndroid#158]
1.提交问题前先查看主页readme中是否有描述相关问题
2.再查看issue板块中是否已经提交过相关问题, 有的话就在此issue中提交问题
3.仍然没有相关描述再创建issue, 注意反馈: 手机型号, 系统版本, Xndroid版本, XX-Net版本, 异常提示. 如果有自动导出日志则附上日志, 如果没有自动导出日志, 则重试出现问题时的操作,再次出现问题后点击菜单中的导出日志. 注意上传整个'xndroid-logs.tar.gz', 如果无法上传,则发送到xndroiddev@gmail.com,并附上上述相关信息.
4.日志和相关信息不要保存在国内网站上. 日志尽量传到issue中, 方便后续查看, 实在无法上传则通过邮箱发送.

**Comment by Chen9833** [comment]
之前试着登陆过一次，随便输的密码，不记得了。
能重置么？

**Comment by SeaHOH** [comment]
可以用注册邮箱给 xxnet.dev@gmail.com 发送邮件请求重置密码。
近段时间 xxnet 比较忙，回复时间可能会比较久。

其实你不该胡乱输入，因为有自动登录。

**Comment by Chen9833** [comment]
感谢！
