### ISSUE TITLE
Xndroid root模式下运行 fqrouter意外退出 日志文件0kb

### ISSUE THREAD

**Issue by WindyNova** [XndroidDev/Xndroid#161]
root模式下运行 fqrouter意外退出 日志文件0kb 三星S3 LTE Android 4.4.4

**Comment by KiansOne** [comment]
三星 Tab S 6.0.1 也是这样

**Comment by XndroidDev** [comment]
vpn模式下是否正常? 使用什么授权工具?

**Comment by KiansOne** [comment]
两个三星vpn进入后 fqrouter界面都是 Internal Server Error
s3使用的是最新SuperSU 2.62 tab s用的是Magisk v16

**Comment by XndroidDev** [comment]
Android 4.4.4可能会有Native运行环境不兼容的问题, 至于Tab S 6.0.1需要更详细的信息

**Comment by KiansOne** [comment]
三星 Tab S 10.5平板 Android 6.0.1 Soc为Samsung Exynos 5420 官方TouchWiz系统 版本号T805CZCU1CQB3 已经安装最新Busybox 症状和Galaxy S3 LTE一样 fqrouter是Internal Server Error
