### ISSUE TITLE
特定网站(www.ingress.com) 出现 permission denied字样无法访问问题(其他网站G歌油管都能上)

### ISSUE THREAD

**Issue by Osss-SJc** [XndroidDev/Xndroid#162]
1.提交2.再查3.仍然4.日志..之后
如题↑↑↑ :
特定网站(www.ingress.com) 出现 permission denied字样无法访问问题(其他网站G歌油管都能上)
且自用windows上XXnet能上

Xndroid 目前最新1.2.3DEBUG
XX-net 自己更新的3.12.11
华为P7 Android4.4.2
麻烦大佬了

**Comment by Osss-SJc** [comment]
@XndroidDev 
@SeaHOH

**Comment by SeaHOH** [comment]
网站限制 GAE 访问而已，可以直连。
