### ISSUE TITLE
安卓版：显示”致命错误“

### ISSUE THREAD

**Issue by whytakemyname** [XndroidDev/Xndroid#165]
安卓最新版。可以正常上网，但是无法进入软件主页面。
打开后显示”致命错误“，点击对话框中退出后直接退出软件，点击其他地方无效。
![44582776-43abb800-a7d5-11e8-83d1-1227c8378523](https://user-images.githubusercontent.com/34732308/44616196-e9b2fd00-a87d-11e8-823a-33f8fecdc486.jpg)
求助
另外希望问下github图片上传失败，总是出现这个是怎么回事（用xxnet连接外网后才能正常上传）
![tim 20180825154353](https://user-images.githubusercontent.com/34732308/44616194-e4ee4900-a87d-11e8-96ab-717d5bf0811e.png)

求助

**Comment by whytakemyname** [comment]
真冷清

**Comment by XndroidDev** [comment]
下载最新版:
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

**Comment by whytakemyname** [comment]
你好，下载最新版后，火狐浏览器无法登陆外网，显示"连接不受信任"。注:证书按照软件界面的要求已经安装到系统，浏览器的代理插件omega无任何改变(之前用的时候能登外网，现在在无任何改动的情况下无法登陆了)

**Comment by XndroidDev** [comment]
火狐有单独的证书管理.
在火狐中访问127.0.0.1:8085,  点击`CA证书状态(下载)` 下载按钮, 在火狐中安装证书

**Comment by whytakemyname** [comment]
按上述方法已解决。感谢。另软件是否目前对于ins无法实现全局代理。看了您在其他问题的回答，基本上都和问题#14有关(好像)。但是开始smartouter之类的怎么开通呢？
另外想问一下，局域网内代理有http和pac代理两种方式，电脑端操作目前已查找问题得以看懂。但是手机没有pac。而是如下内容
主机名：
端口:
例外网址:
像这种情况是用http就好吗？其实是想问下什么时候用http,什么时候用pac.(三个手机上都没看到pac这三个字母)
劳烦您了。感谢

**Comment by XndroidDev** [comment]
1. https://github.com/XndroidDev/Xndroid/issues/14#issuecomment-351730982
2. Android 设置中不支持pac设置, fqrouter进行透明代理也不会使用pac. 默认设置下(见fqrouter-代理列表-配置),国内ip及域名直连, 其余走代理(见fqrouter代理列表), 如有特殊要求可添加白名单域名(见readme)

**Comment by whytakemyname** [comment]
你好，fqrouter-代理列表-配置后显示“配置代理-优先个人代理”。
想问下您说的是不是fqrouter-代理列表-http代理。
手机上的主机名是不是填http后面的地址26.26.26.1:2516
端口是不是软件配置里的端口。
您说的似乎是自己的代理，然后里面的默认设置就是您写的那样。原谅我没有看懂，我想表述的是局域网分享以使别的可以上外网。辛苦了

**Comment by AnyWAT** [comment]
https://github.com/XX-net/XX-Net/issues/11293#issuecomment-414025798 https://github.com/XX-net/XX-Net/issues/11293#issuecomment-414030364

**Comment by XndroidDev** [comment]
未root下有两种方式:
1. 开启HTTP代理旁的开关, 在同一网段需要代理的设备上设置http代理或pac代理, 设置主机为手机在局域网下的ip(见fqrouter提示, 或wlan高级设置), 端口默认2516.
2. 点击Pick&Play旁的扫描点击相应设备
更多代理方式见readme
无论使用什么代理方式, 只要使用了GAE, 就必须在所有设备上安装证书!!!

**Comment by whytakemyname** [comment]
感谢

**Comment by whytakemyname** [comment]
非常谢谢
