### ISSUE TITLE
提示连接成功，但仍然无法冲浪。

### ISSUE THREAD

**Issue by AudreyYuSuenSH** [XndroidDev/Xndroid#172]
手机型号：vivo X21A
系统版本：安卓 8.1.0
Xndroid版本：1.2.3 Debug
XX-Net版本：3.12.10

日志：
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2400880/xndroid-logs.tar.gz)

### - 显示连接成功，状态如下图（6张）：

![01](https://user-images.githubusercontent.com/16278231/45815726-1dae0080-bd0c-11e8-8c30-d0da174d0d03.jpg)
![02](https://user-images.githubusercontent.com/16278231/45815368-002c6700-bd0b-11e8-8914-6248e8e778ba.jpg)
![03](https://user-images.githubusercontent.com/16278231/45815377-06224800-bd0b-11e8-93d4-f29387be43a8.jpg)
![04](https://user-images.githubusercontent.com/16278231/45815856-86957880-bd0c-11e8-9f06-bcc0226db0d0.jpg)
![05](https://user-images.githubusercontent.com/16278231/45815396-13d7cd80-bd0b-11e8-964f-72378da2cd57.jpg)
![06](https://user-images.githubusercontent.com/16278231/45815401-189c8180-bd0b-11e8-8e6b-bf991e6e2883.jpg)

### - 以下是打开 “google play商店” “xndroid内置 lighting browser 试图打开 chrome” “尝试 chrome 官网下载” 的结果返回页面：

![11](https://user-images.githubusercontent.com/16278231/45815519-89439e00-bd0b-11e8-8579-e13baf2d70b5.JPG)
![22](https://user-images.githubusercontent.com/16278231/45815525-8e085200-bd0b-11e8-99ef-3009ee112ad0.JPG)
![33](https://user-images.githubusercontent.com/16278231/45815529-93659c80-bd0b-11e8-82fc-f0dcee0999b7.JPG)
![44](https://user-images.githubusercontent.com/16278231/45815540-98c2e700-bd0b-11e8-8941-2e03dcb23170.JPG)
![55](https://user-images.githubusercontent.com/16278231/45815547-9d879b00-bd0b-11e8-8d90-144d0faa53bd.JPG)

**Comment by AnyWAT** [comment]
试试：关闭自动调整扫描线程开关（2处），软件首页及XX-Net 的GAEPROXY各有一个功能相同的开关。
有效 IP数会达到总 IP数、IP延时会减小，然后会有不同于现在的结果😂

**Comment by XndroidDev** [comment]
1. app访问异常: https://github.com/XndroidDev/Xndroid/issues/32 若需在非浏览器中使用, 尝试导入为系统证书(需root)

2. 网页访问异常: 尝试更新内置XX-Net, 或反馈到 https://github.com/XX-net/XX-Net/issues

**Comment by Beyood** [comment]
在没有ROOT的情况下，排除局域网内部问题试试先使用移动网络成功设置，正常使用一段时间后再连接WIFI。

**Comment by Chriszhung** [comment]
今天晚上开始，显示一切正常，app都打不开

**Comment by Chriszhung** [comment]
今天晚上开始，显示一切正常，app都打不开
