### ISSUE TITLE
有方法固定一个teredo服务器么？

### ISSUE THREAD

**Issue by diyici18sui** [XndroidDev/Xndroid#173]
1.提交问题前先查看主页readme中是否有描述相关问题
2.再查看issue板块中是否已经提交过相关问题, 有的话就在此issue中提交问题
3.仍然没有相关描述再创建issue, 注意反馈: 手机型号, 系统版本, Xndroid版本, XX-Net版本, 异常提示. 如果有自动导出日志则附上日志, 如果没有自动导出日志, 则重试出现问题时的操作,再次出现问题后点击菜单中的导出日志. 注意上传整个'xndroid-logs.tar.gz', 如果无法上传,则发送到xndroiddev@gmail.com,并附上上述相关信息.
4.日志和相关信息不要保存在国内网站上. 日志尽量传到issue中, 方便后续查看, 实在无法上传则通过邮箱发送.
5.发现APP bug或无法使用, 请先尝试安装最新测试版(https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk)

坐标北京，近期发现195.140.195.140这个teredo服务器有时候不稳定，在teredo.py中有四个服务器地址，请问有什么方法能固定某一个么？在首页更换服务器处 固定一个 比如 157.56.106.185 在下次打开软件的时候，又会重新选择一个~很困扰。
求大神解答

**Comment by diyici18sui** [comment]
![image](https://user-images.githubusercontent.com/33658823/45871421-0d575d80-bdc0-11e8-8d25-cebcd966d514.png)
附上刚刚联通专线的测试图

**Comment by XndroidDev** [comment]
当teredo掉线后会自动更换teredo服务器, 目前普通用户无法更改. 超级用户可修改teredo.py, 服务器列表中只留一个ip即可

**Comment by diyici18sui** [comment]
@XndroidDev 感谢解答！

**Comment by diyici18sui** [comment]
@XndroidDev 感谢解答！
