### ISSUE TITLE
路由拨号获得原生IPV6后仅IPV6不可用

### ISSUE THREAD

**Issue by Beyood** [XndroidDev/Xndroid#174]
原先IPV4网络环境下使用一切正常，获取公网原生IPV6后，Xndroid自动关闭teredo，之后就无法使用了。
切换到移动网络，问题依旧，尝试在“高级”中设置原生IVP6优先也没有反应。

XX-Net Status:

sys-platform: armv7l, Linux-4.4.23+-armv7l-with-libc
os-system: Linux
os-version: #1 SMP PREEMPT Thu Aug 9 00:25:59 CST 2018
os-release: 4.4.23+
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 8.0.0; MHA-AL00 Build/HUAWEIMHA-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 Mobile Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.2
openssl-version: 16.2.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:undefined ipv4:0 ipv6:91
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0 used:undefined
worker: h1:0 h2:0
scan-ip-thread-num: 12
ip-quality: 745
is-idle: 0
block-stat: undefined
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by AnyWAT** [comment]
https://github.com/XndroidDev/Xndroid/issues/119

**Comment by Beyood** [comment]
> 
> 
> #119

非常感谢，没注意有这个菜单，原生IPV6无法连接，但不勾选“IPV6可用时禁用teredo”，还是用6to4的办法使用正常。
