### ISSUE TITLE
X-Tunnel登录问题

### ISSUE THREAD

**Issue by MooreY** [XndroidDev/Xndroid#178]
每次切换回xtunnel都会重新登录账号密码

**Comment by XndroidDev** [comment]
如何切换的?

**Comment by MooreY** [comment]
> 如何切换的?

从后台回到xndroid

**Comment by MooreY** [comment]
> > 如何切换的?
> 
> 从后台回到xndroid
不过好像并不影响，不会断开连接

**Comment by MooreY** [comment]
> 如何切换的?
还有个想问的问题就是gae那里的总ip一直只是是200，导致ip延迟过高，这个怎么解决？

**Comment by XndroidDev** [comment]
开启"自动扫描线程后"会更据ip数, 时延, 电量, 网络状态自动调整最大扫描线程数,  ip延迟过高时会自动加大扫描线程数

**Comment by Chriszhung** [comment]
XTunnel登不上去了，602

**Comment by AnyWAT** [comment]
貌似X-Tunnel 服务器已恢复😂

**Comment by Chriszhung** [comment]
还是602，没有恢复

**Comment by AnyWAT** [comment]
又回到了不正常而已😜

**Comment by Chriszhung** [comment]
Xtunel还是不能用

**Comment by XndroidDev** [comment]
反馈到https://github.com/XX-net/XX-Net/issues
