### ISSUE TITLE
什么时候更新，能使app应用代理可用啊？

### ISSUE THREAD

**Issue by panpeach** [XndroidDev/Xndroid#18]
play商店，Telegram等应用都打不开无法使用。
浏览器打开还行，youtube速度偏慢，480都一卡一卡的
有时间的话能不能开发个goproxy IPV6应用啊，PC端的goproxy IPV6， 比xx-net IPV6 快上好几倍。
![gop1](https://user-images.githubusercontent.com/13916352/33794516-9e2f014e-dd08-11e7-8e9d-5fcf0fdb046a.jpg)

**Comment by XndroidDev** [comment]
goproxy 以后再研究
https://github.com/XndroidDev/Xndroid/issues/14
