### ISSUE TITLE
怎么使用带有密码的appid

### ISSUE THREAD

**Issue by zx09** [XndroidDev/Xndroid#183]
怎么使用带有密码的appid
这个没有appid很不好用吧 我root了

**Comment by izcbc** [comment]
wiki---
关于修改XX-NET配置

一般无需也不建议手动修改XX-NET配置文件. 如特殊情况需要修改, root用户可直接修改相关文件, 其位于/data/data/net.xndroid/files/xndroid_files/xxnet/; 非root用户可以下载XX-NET zip压缩包, 将其解压, 并修改或添加相应文件再压缩回zip, 点击菜单中的离线更新XX-NET, 选择修改的zip文件即可

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/44
或者你可以暂时先用公共appid
