### ISSUE TITLE
原生ipv6环境下不可用

### ISSUE THREAD

**Issue by Mybestway** [XndroidDev/Xndroid#185]
看前面的提问，好像新版支持原生ipv6环境了。但当我在“启动设置”里禁用teredo后，“ipv6状态”fail，”连接尚未建立“，一定要开启隧道后才能连接，是什么问题呢？
xndroid版本1.2.5，xxnet版本3.12.10，android6.0，wifi下原生ipv6。

**Comment by iopxiang** [comment]
1.2.5原生ipv6判断错误，1.2.4反而没问题

**Comment by XndroidDev** [comment]
ipv6判断错误具体是什么情况，提供一下日志

**Comment by iopxiang** [comment]
> ipv6判断错误具体是什么情况，提供一下日志

就是我有原生的ipv6地址，也选择了ipv6环境下自动禁用teredo，但是还是开启了teredo，而1.2.4能正确识别原生ipv6环境

**Comment by XndroidDev** [comment]
最新版已解决判断错误

**Comment by XndroidDev** [comment]
部分地区原生ipv6已被墙无法使用GAE, 仍然需要走隧道.
