### ISSUE TITLE
填写了自己appid不能FQ，留空反而可以用，大家帮忙看看什么原因

### ISSUE THREAD

**Issue by laowai567** [XndroidDev/Xndroid#186]
问题如标题描述，如何才能使用自己的appid？大家知道什么原因吗？有没有遇到同样的问题？
自己的appid在电脑上是可以正常使用的。

![11](https://user-images.githubusercontent.com/28185849/48205345-09e75800-e3a7-11e8-8a05-ad0a5ab4a55b.png)

![12](https://user-images.githubusercontent.com/28185849/48205257-e15f5e00-e3a6-11e8-8231-d7595f3ef710.png)

**Comment by kaka6119** [comment]
密码错误

**Comment by laowai567** [comment]
在哪里可以输入密码？
手机上没找到配置密码的地方

**Comment by AnyWAT** [comment]
貌似：如手机Root 了，复制在电脑上是可以正常使用的 config.json 的相应部分到手机（同名文件）？否则，留空（用不带密码的公共AppID）反而可以用😂

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/44
