### ISSUE TITLE
一直显示连接尚未建立，求救，下面是诊断信息

### ISSUE THREAD

**Issue by donqu** [XndroidDev/Xndroid#187]
XX-Net Status:

sys-platform: armv8l, Linux-4.9.65-perf-ga280a16-armv8l-with-libc
os-system: Linux
os-version: #1 SMP PREEMPT Tue Oct 16 00:32:27 CST 2018
os-release: 4.9.65-perf-ga280a16
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 8.1.0; MI 8 Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36
xxnet-version: 3.12.10
python-version: 2.7.2
openssl-version: 16.2.0 TLSv1_2 h2:alpn
lan-proxy: Disable
use-ipv6: force_ipv6
gws-ip-num: total:50 ipv4:0 ipv6:50
ipv4-status: OK
ipv6-status: Fail
connected-link: new:0
worker: h1:0 h2:0
scan-ip-thread-num: 12
ip-quality: 100
is-idle: 0
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by XndroidDev** [comment]
teredo是否被禁用？

**Comment by XndroidDev** [comment]
xxnet更新到最新版试试
