### ISSUE TITLE
装了fqrouter后，换用影梭或是别的VPN，app也翻不动了。

### ISSUE THREAD

**Issue by samanxx** [XndroidDev/Xndroid#188]
我用的是fqrouter的root模式，知道因为证书的原因，gae翻只能用浏览器，用不了app，
确实浏览器翻起来也没问题，googleplay可以打开，其它app打不开。
但是我退出fqrouter后，用影梭或者是别的vpn，用的是全局模式，
用浏览器和googleplay还是正常能打开，但是twitter,facebook,instagram等app还是翻不动。
上网搜说要把影梭里IPv6 Route 和 DNS Forwarding 两个选项关掉也试过了，vpn是没有这两个选项。
也去手机的安全设置里把xx-net的证书给禁用掉，还是不行。
还试过装了禁用ipv6手动把ipv6给禁用，这样禁用xx-net就会提示ipv6不可用，翻不动，
再开影梭和vpn也还是翻不动。搞不懂是什么原因，现在变成只有浏览器和googleplay是能正常翻的。

**Comment by samanxx** [comment]
白天发完issue，又开了次fqroute，可能是忘了用左上角的exit退出，而是直接把fqroute划掉，所以晚上再开fqroute的时候像第一次一样提示要vpn模式还是root模式，这次选了vpn模式，然后正常用exit退出。再开影梭和其它vpn，APP都能正常翻了。所以是root模式的锅吗?以后还是选VPN模式吧。

**Comment by XndroidDev** [comment]
"直接把fqroute划掉"只是把activity给强行终止, root模式下后台进程还会运行, 因此用完后需要点`退出`
