### ISSUE TITLE
google play

### ISSUE THREAD

**Issue by kaka6119** [XndroidDev/Xndroid#189]
已经开启X-tunnel模块，youtube应用可以访问，但为什么谷歌商店打不开

**Comment by yuye12345chen** [comment]
xndroid已经挂了

**Comment by xxnet** [comment]
升级里面的XX-Net就可以了

**Comment by rarechit** [comment]
> 最新版了，IP满血，但还是无法访问Google play和youtube客户端

root了吗，安卓N在root后没问题，今天还没试试，貌似需要更新xxnet

**Comment by XndroidDev** [comment]
转至 https://github.com/XndroidDev/Xndroid/issues/191

**Comment by devilwit** [comment]
手机已经root，Xndroid可用。
但是试图打开谷歌play商店时报服务器连接错误，但是用其他的VPN可以，所以应该不是网络或者手机的问题。
求助

**Comment by AnyWAT** [comment]
> 求助

见你的LS，https://github.com/XndroidDev/Xndroid/issues/191#issuecomment-449705387
