### ISSUE TITLE
XXNET无法更新到最新

### ISSUE THREAD

**Issue by ToARuGo** [XndroidDev/Xndroid#190]
12月20日XXNET更新了，说是google更改了策略，旧版都不能上网了。到Xndriod里下载XXNET新版后却无法装上，提示unzip失败。软件里手动管理的下拉选项里也没有已经下载好的包。

**Comment by ALeeCJ** [comment]
同样出现这种情况了，但是重新打开软件发现已经更新到13了

**Comment by maoyali** [comment]
请问怎么更新啊？我的右上角下拉菜单更新XX-NET用不了

**Comment by jj-sun** [comment]
可以手动更新啊，软件都有说明的。右上角，离线更新XX-Net,里面有说如何离线更新。下载xx-net，github上的是.7z格式的，下载后解压，再压缩成zip，命名为XX-Net.zip，放在手机文件根目录下即可。然后点击右上角，离线更新，弹框下面会有更新的按钮，点击即可。

**Comment by XndroidDev** [comment]
xndriod内置xxnet已更新
