### ISSUE TITLE
无法下载google play的应用

### ISSUE THREAD

**Issue by 990753707** [XndroidDev/Xndroid#191]
之前在google play 是可以正常使用的，前两天突然不能用了，整个翻墙都失败，后来升级了xx-net，可以正常使用google搜索和youtube，google play 也可以正常打开，但是就是不能下载和更新，一直转。不是网络的问题。
xx-net 版本：3.13.1
xndroid 版本： 1.25

**Comment by peter-wang-wsl** [comment]
这个项目应该没人维护了，我这延迟大，可用ip少

**Comment by peter-wang-wsl** [comment]
> 
> 
> 之前在google play 是可以正常使用的，前两天突然不能用了，整个翻墙都失败，后来升级了xx-net，可以正常使用google搜索和youtube，google play 也可以正常打开，但是就是不能下载和更新，一直转。不是网络的问题。
> xx-net 版本：3.13.1
> xndroid 版本： 1.25

这个项目应该没人维护了，我这延迟大，可用ip少

**Comment by xxnet** [comment]
这批gae的ip，无法支持google play和scholar，需要专门针对这些应用找一批ip，还有建专用通道，代码改动较大，先放后面吧

**Comment by peter-wang-wsl** [comment]
> 
> 这批gae的ip，无法支持google play和scholar，需要专门针对这些应用找一批ip，还有建专用通道，代码改动较大，先放后面吧

大牛辛苦

**Comment by 990753707** [comment]
> 这批gae的ip，无法支持google play和scholar，需要专门针对这些应用找一批ip，还有建专用通道，代码改动较大，先放后面吧

辛苦了

**Comment by AnyWAT** [comment]
几乎完美的替代 https://m.apkpure.com https://apkpure.com
