### ISSUE TITLE
怎样设置whatsapp使用xndroid连接？

### ISSUE THREAD

**Issue by Telaea** [XndroidDev/Xndroid#194]
使用蓝灯VPN FQ时，可设置哪些应用通过蓝灯，哪些不通过；蓝灯的弱点是偶尔能上网；
但使用Xndroid FQ时（能FQ上网），没找到蓝灯类似的设置地方，似乎whatsapp没能通过Xndroid连网络（whatsapp连不上），请问怎样设置？

**Comment by XndroidDev** [comment]
xndroid启动后为全局代理，目前不支持分应用设置，部分应用无法使用应该是证书问题
https://github.com/XndroidDev/Xndroid/issues/14

**Comment by XndroidDev** [comment]
GAE代理无法彻底解决证书问题, 不过root后导入为系统证书可以使大部分应用信任
