### ISSUE TITLE
如何使华尔街日报通过Xndroid的X-TUNNEL联网？

### ISSUE THREAD

**Issue by varicella** [XndroidDev/Xndroid#195]
看了之前的一些帖子，试了以下的办法都无法使华尔街日报通过该软件更新。但是chrome使用google没有问题，facebook、twitter、youtube没有问题。但就是华尔街日报和google play不行
首先已经在fqroute中设置socks5代理127.0.0.1:1080，同时删除HTTP代理，并登录X-TUNNEL账号。
1、关闭Smart router。
2、打开smart router，设置黑名单X-TUNNEL。
3、打开smart router，设置全局smat router
4、打开smart router，设置黑名单X-TUNNEL，禁止自动直连
5、打开smart router，设置黑名单X-TUNNEL，禁止自动直连，禁止自动尝试GAEProxy

上面5种设置了都无法更新，是不是哪里出现问题了？

**Comment by XndroidDev** [comment]
xtunnel连接不稳定，你可以反馈到
https://github.com/XX-net/XX-Net/issues

**Comment by AnyWAT** [comment]
> xtunnel连接不稳定

https://github.com/XX-net/XX-Net/issues/11892 附：3、X-Tunnel 正常的前提。。。
参考：https://github.com/XX-net/XX-Net/issues/12043

> 上面5种设置了都无法更新，是不是哪里出现问题了？

试试：楼主的2、或3、再+ http://127.0.0.1:8085/?module=smart_router&menu=config 通用—— PAC 策略——黑名单-> X-Tunnel
