### ISSUE TITLE
Nexus 6 7.1.2 未全局代理

### ISSUE THREAD

**Issue by OvlTkm** [XndroidDev/Xndroid#2]
的確是請求了VPN權限，而且系統狀態欄也有鑰匙圖案。
但是目前發現Google Play, YouTube, Google App提供的天氣都提示不能連接到網絡。
Chrome Dev可以正常訪問Twitter等網站

**Comment by XndroidDev** [comment]
感谢反馈,就是说浏览器可以正常访问,但其他应用不行吗.

**Comment by OvlTkm** [comment]
剛才又試了一遍。
Chrome Dev 和 Firefox 都可以。但是應用的話似乎只有Gmail和Google Keep（不確定，但是Gmail是的確刷新出了郵件內容）。此外很奇怪的是國產軟件都可以聯網，而且似乎是走代理的（因為速度明顯更慢）。
這次因為人在外面，是用數據流量測的。上次是WiFi。
