### ISSUE TITLE
使用中的问题

### ISSUE THREAD

**Issue by ydjoe** [XndroidDev/Xndroid#20]
不管是软件自带的appid还是自己的appid,都连不上谷歌服务，谷歌搜索youtube都使用不了，显示net::ERR_CONTENT_DECODING_FAILED.其他比如FB，推特都正常，请求解决这个问题

**Comment by XndroidDev** [comment]
参考 https://github.com/XX-net/XX-Net/issues/8852

**Comment by XndroidDev** [comment]
br编码问题已修复, 请更新到最新版
