### ISSUE TITLE
全局代理需要设置什么吗？

### ISSUE THREAD

**Issue by hunshenshi** [XndroidDev/Xndroid#206]
无法实现全局代理，只能在app内通过浏览器fq

具体怎么实现全局代理呀？望大神给个教程

**Comment by AnyWAT** [comment]
貌似新装 Xndroid 1.3.0 默认全局 smart_router 代理（且未开启 X-Tunnel 与 Smart Router 模块），非新装的已 root 的手机，退出应用可修改 config.yaml 实现。至于是否有效果，自己验证？
![image](https://user-images.githubusercontent.com/37962734/53679834-2ec45a00-3d0d-11e9-9c99-c6e387b49f8c.png)

**Comment by hunshenshi** [comment]
@AnyWAT 没明白呀，在未开启 X-Tunnel 与 Smart Router 模块时，默认是全局smart_router代理，没有开启smart_router模块smart_router代理可以用？
已root的手机改下config的配置，这是必须的？没有root的手机不能开启全局代理？

**Comment by AnyWAT** [comment]
> @AnyWAT 没明白呀，在未开启 X-Tunnel 与 Smart Router 模块时，默认是全局smart_router代理，没有开启smart_router模块smart_router代理可以用？

或许与电脑版本的差异所在？@XndroidDev

> 已root的手机改下config的配置，这是必须的？没有root的手机不能开启全局代理？

参考：https://github.com/XndroidDev/Xndroid 关于修改XX-NET配置：非root用户可以[下载XX-NET zip压缩包](https://github.com/XX-net/XX-Net/releases), 将其解压, 并修改或添加相应文件再压缩回zip, 点击菜单中的离线更新XX-NET, 选择修改的zip文件即可.

**Comment by XndroidDev** [comment]
默认全局代理，无需设置。如果其他应用内无法使用，可能是证书问题

**Comment by xwtxwy** [comment]
可以用这个就一键翻了 http://js.buylure.com/share.html?channel=kdl16

**Comment by xwtxwy** [comment]
可以用这个就一键翻了 [下载地址](http://js.buylure.com/share.html?channel=kdl16) 不用设置了
