### ISSUE TITLE
请问如何使用ipv6

### ISSUE THREAD

**Issue by czroblerao** [XndroidDev/Xndroid#21]
安装后，正常启动。但是无法使用ipv6,请问该怎么设置？
![screenshot_2017-12-10-21-14-06](https://user-images.githubusercontent.com/34417357/33805215-108f27ea-ddf0-11e7-915c-8d95eeefbd33.png)

**Comment by XndroidDev** [comment]
正常的话无需为IPV6设置,截图上没有看出明显的问题.你可以将日志发过来

**Comment by ThinkerQAQ** [comment]
同样的问题,no enough ip

**Comment by XndroidDev** [comment]
@czroblerao  @ThinkerQAQ 
请说明你们的手机系统版本和型号
参考 https://github.com/XndroidDev/Xndroid/issues/23

可能是因为手机rom 的bug(或被阉割)

**Comment by XndroidDev** [comment]
是否能正常访问国内站点

**Comment by zangkong** [comment]
同样的问题ipv6状态错误 坚果pro

**Comment by ThinkerQAQ** [comment]
似乎移动的数据网络就不行,换成其他的就可以
