### ISSUE TITLE
chrome部分正常，APP异常

### ISSUE THREAD

**Issue by ronnieli1702** [XndroidDev/Xndroid#210]
一、目前存在的问题：
1.使用手机chrome可正常访问除google play之外的其他网站（chrome下访问google play显示“抱歉，出现错误。请稍后重试。”）
2.google play（APP）显示“从服务器检索信息时出错。DF-DFERH-01”
3.google旗下youtube（APP）同样无法访问。
二、设备
1.华为V20
2.版本：9.0.1.143（C00E141R2P2） GPU Turbo
3.安卓9
4.Xndroid1.3.0稳定版
5.XX-NET3.13.1
三、日志文件
1.日志文件为本次chrome访问play以及APP直接打开play两种情况。
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2999070/xndroid-logs.tar.gz)
最后，个人比较小白，主要就是想要APP正常访问GOOGLE PLAY和YOUTUBE，先行感谢。

**Comment by AnyWAT** [comment]
貌似因证书等原因GAE不行，X-Tunnel 倒行？貌似分享其它设备如电脑运行的XX-Net 代理倒也行？

**Comment by ronnieli1702** [comment]
补充：
1.使用其他梯子可使用APP正常访问play和youtube，并且在play中建立下载任务后，若更换Xndroid，可正常下载且速度很快。
2.在PC、华为麦芒4以及P8，Xndroid均可正常使用。

**Comment by ronnieli1702** [comment]
> 貌似因证书等原因GAE不行，X-Tunnel 倒行？貌似分享其它设备如电脑运行的XX-Net 代理倒也行？

之前也试了清除锁屏后导入证书，在导入的过程中要求设置锁屏密码。依然无效。

**Comment by AnyWAT** [comment]
> 依然无效

因GOOGLE PLAY和YOUTUBE不认XX-Net 证书的原因GAE不行，X-Tunnel 倒行？
试试：分享其它设备如电脑运行的XX-Net 代理

**Comment by funic** [comment]
问题相同，app不行，显示没有网络，浏览器可以, 不过ip掉得很快

**Comment by AnyWAT** [comment]
> ip掉得很快

关闭首页的"自动调整。。。"及GAEProxy 高级配置内的"自动调整扫描线程数"

**Comment by ronnieli1702** [comment]
> > 依然无效
> 
> 因GOOGLE PLAY和YOUTUBE不认GAE证书的原因GAE不行，X-Tunnel 倒行？
> 试试：分享其它设备如电脑运行的XX-Net 代理

试了下，还是不行。安卓9必须root之后导入证书吗？

**Comment by AnyWAT** [comment]
> 试了下，还是不行。安卓9必须root之后导入证书吗？

行，得已导入证书为前提。https://github.com/XndroidDev/Xndroid/issues/210#issuecomment-475845471 二楼就说到了证书，还有

> 2.在PC、华为麦芒4以及P8，Xndroid均可正常使用。

如此多经历，现在才说：安卓9必须root之后导入证书吗？没安卓9的怎知？
https://github.com/XndroidDev/Xndroid 注意一些APP(如 Twitter, Facebook 等)由于不信任GAE的证书,可能无法正常访问网络, 建议在浏览器中使用.

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/14
https://github.com/XndroidDev/Xndroid/issues/32
见README
