### ISSUE TITLE
我装完软件之后在xx-net界面没有xtunnel选项，xndroid版本1.3 1，xx-net版本3.13.1

### ISSUE THREAD

**Issue by JIBSN** [XndroidDev/Xndroid#212]
1.提交问题前先查看主页readme中是否有描述相关问题
2.再查看issue板块中是否已经提交过相关问题, 有的话就在此issue中提交问题
3.仍然没有相关描述再创建issue, 注意反馈: 手机型号, 系统版本, Xndroid版本, XX-Net版本, 异常提示. 如果有自动导出日志则附上日志, 如果没有自动导出日志, 则重试出现问题时的操作,再次出现问题后点击菜单中的导出日志. 注意上传整个'xndroid-logs.tar.gz', 如果无法上传,则发送到xndroiddev@gmail.com,并附上上述相关信息.
4.日志和相关信息不要保存在国内网站上. 日志尽量传到issue中, 方便后续查看, 实在无法上传则通过邮箱发送.
5.发现APP bug或无法使用, 请先尝试安装最新测试版(https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk)

**Comment by AnyWAT** [comment]
> 装完软件之后在xx-net界面没有xtunnel选项

xx-net界面的（系统）配置——模块管理——启用 X-Tunnel：ON

**Comment by JIBSN** [comment]
@AnyWAT 谢谢，xtunnel是不是在手机上用不了了，我在电脑是能用xtunnel，但是手机上一直连不上，手机没root。

**Comment by AnyWAT** [comment]
在手机上能用。一直连不上或因主力前端性能不佳，参照 https://github.com/XX-net/XX-Net/issues/12455 提升XX-Net 性能（需 root 后才能修改的参数如增大总 IP数等则免了），关闭“自动调整扫描线程数”貌似在软件首页及 xx-net 界面内各有一个（相同功能？）开关
PS：软件左上角菜单设置 xtunnel 。。。（ issue 内自搜索）

**Comment by JIBSN** [comment]
@AnyWAT 我已经买了xtunnel，我直接把代理端口设置为1080了，8087端口删了。感觉用xtunnel几乎连不上，gae偶尔还能连上，是我哪里设置的不对吗

**Comment by AnyWAT** [comment]
> 8087端口删了。感觉用xtunnel几乎连不上，gae偶尔还能连上，是我哪里设置的不对吗

强化主力前端 GAE：Teredo 隧道 https://github.com/XX-net/XX-Net/issues/12455 或原生 https://github.com/XX-net/XX-Net/issues/12477
GAE（前端）正常，貌似检测证书的 *.deja.com 需走GAE，8087端口删了则谬矣？
如用隧道，所用隧道是。。。及XX-Net 诊断信息。。。

**Comment by AnyWAT** [comment]
将手机上类似截图发上来？

![image](https://user-images.githubusercontent.com/37962734/58190153-7cd67180-7cee-11e9-85e7-3d66ac141856.png)

**Comment by AnyWAT** [comment]
> PS：软件左上角菜单设置 xtunnel 代理。。。（ issue 内自搜索）

软件首页左上角菜单——Fqrouter ——（最后的）代理列表——添加代理——Socks5 127.0.0.1：1080
