### ISSUE TITLE
咨询一个技术问题，为什么走http代理需要导入证书，x_tunnel走sock5代理不需要导入证书

### ISSUE THREAD

**Issue by UchihaKutter** [XndroidDev/Xndroid#216]
最近手机已经root, 证书已导入系统信任，但是还是有一些app无法翻墙，原因是这些app不信任gae证书，但是走x_tunnel就可以，这里有个技术问题，为什么走http代理需要导入证书，x_tunnel走sock5代理不需要导入证书。

**Comment by XndroidDev** [comment]
因为GAE代理不是socket转发, 需要解析传输内容来"模拟"http代理. 真正的http代理不需要而外导入证书
