### ISSUE TITLE
1.3.1版本如附图，一直显示“无足够可用ip,稍等片刻”等半天了还是这样。

### ISSUE THREAD

**Issue by rrn21833** [XndroidDev/Xndroid#221]
![Screenshot_2019-12-06-12-13-58](https://user-images.githubusercontent.com/37966911/70296287-f5f86a80-17e1-11ea-8e15-f67b65324dc2.png)

**Comment by XndroidDev** [comment]
抱歉, 这个和你的环境有关. 目前很多环境下GAE已经无法正常使用, 如果可以的话, 请添加SS代理
