### ISSUE TITLE
安卓在全局模式或者指定APP代理都对steam没有效果

### ISSUE THREAD

**Issue by yz-xlame** [XndroidDev/Xndroid#223]
安卓在全局模式或者指定APP代理都对steam没有效果，我手机steam还是连不上

**Comment by yz-xlame** [comment]
但是确实能够翻墙了

**Comment by XndroidDev** [comment]
应该是证书问题, 参考:
https://github.com/XndroidDev/Xndroid/issues/14

**Comment by yz-xlame** [comment]
@XndroidDev 我在开始的时候就安装了证书
