### ISSUE TITLE
app停留在启动vpn服务，无响应

### ISSUE THREAD

**Issue by hellofxin** [XndroidDev/Xndroid#25]
第一次安装成功后，可以自由上网，然后卸载了一次，同时把app创建的vpn连接删除，第二次安装打开后出现问题，无法启动vpn

**Comment by ylwszb** [comment]
重启手机试试……

**Comment by hellofxin** [comment]
（开发）可以试试打开vpn前检查vpn是否创建，可能可以避免出现打开vpn无响应，close了
