### ISSUE TITLE
自动更新1.1.3后，原有配置全清空了？

### ISSUE THREAD

**Issue by panpeach** [XndroidDev/Xndroid#26]
自最初版本一路更新以来，用户配置文件都在，今天启动提示升级，升级后用户所有配置文件都没了。
appid需重新输入，证书也要重新导入，原有5~6千个ipv6 IP也没了，xx-net又要重新升级
这次升级就好像是全新安装？

**Comment by XndroidDev** [comment]
XX-Net的启动相关的代码有改动, 为了保证能正常运行, 就先删掉了XX-Net.  
xx-net 可以不用更新, 用内置的就好. 
IPv6  的IP数量不在于多, 有几十个能用的够了, 几分钟就能扫出来

**Comment by iopxiang** [comment]
appid每次退出都清除了？证书导入失败，文件不存在，1.1.2版在android 7.0上

**Comment by XndroidDev** [comment]
@iopxiang 
卸载后安装1.1.3, 仍然出现问题再把日志发过来
