### ISSUE TITLE
Python 初始化失败

### ISSUE THREAD

**Issue by iopxiang** [XndroidDev/Xndroid#29]
1.1.4 on Android 7.0
![screenshot_20171218-101526](https://user-images.githubusercontent.com/26472247/34087355-75e0f3c4-e3dd-11e7-8e9f-256313839d78.png)

**Comment by XndroidDev** [comment]
有过一个反馈， 是权限问题
https://github.com/XndroidDev/Xndroid/issues/22
目前不清楚为什么chmod执行后仍然不可读

**Comment by XndroidDev** [comment]
你有给root权限吗

**Comment by iopxiang** [comment]
给了root权限

**Comment by XndroidDev** [comment]
[app-debug.apk.zip](https://github.com/XndroidDev/Xndroid/files/1567018/app-debug.apk.zip)
(先去掉.zip拓展名) 卸载后安装这个, 将日志发过来.
@iopxiang  @lunjielee

**Comment by iopxiang** [comment]
[xndroid-logs.tar.gz.zip](https://github.com/XndroidDev/Xndroid/files/1570009/xndroid-logs.tar.gz.zip)

**Comment by lunjielee** [comment]
抱歉，才看见。这次变成xxnet启动失败了

**Comment by XndroidDev** [comment]
@lunjielee   日志发过来

**Comment by XndroidDev** [comment]
看来和magic 有关， shell命令得到的文件权限有点怪

**Comment by XndroidDev** [comment]
@iopxiang  @lunjielee  
麻烦重新卸载后测试这个 https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk   无论是否正常运行都将日志发过来

**Comment by 785045633** [comment]
[xndroid-logs.tar(1).gz](https://github.com/XndroidDev/Xndroid/files/1573784/xndroid-logs.tar.1.gz)
一加3，8.0，启动失败后直接死机.
![screenshot_20171220-085316](https://user-images.githubusercontent.com/34326489/34186062-69bfc5d8-e564-11e7-8d3d-9a0c5341df8e.jpg)

**Comment by XndroidDev** [comment]
Android 7.0 以上的文件权限很奇怪，即使chmod，chown，chgrp  java进程中一直不可读, 不知道是不是Android 故意限制的。 @iopxiang  @lunjielee  @785045633  ，你们用的什么授权工具， SuperSU 还是 magisk
还有
>CANNOT LINK EXECUTABLE "getprop": "/data/data/net.xndroid/files/xndroid_files/python/lib/libcrypto.so.1.0.0" is 32-bit instead of 64-bit

看来Android对native进程越来越不友好了， 还是我的Android 6.0 好用

**Comment by XndroidDev** [comment]
@785045633   你试试**清除应用数据或卸载后**   **不要给root权限**，能否正常使用。

注意：清除应用数据或卸载后再试

**Comment by iopxiang** [comment]
@XndroidDev 我用的magisk

**Comment by gogo008** [comment]
用了debug版还是不行（SuperSU，手机：三星note5），日志如下：
[root模式下xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1574056/root.xndroid-logs.tar.gz)
[VPN模式下xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1574057/VPN.xndroid-logs.tar.gz)
![20171220_111916](https://user-images.githubusercontent.com/29323256/34189926-fa1c5286-e578-11e7-889c-6ef4a57f8765.png)
![screenshot_20171220-111812](https://user-images.githubusercontent.com/29323256/34189928-fa64b292-e578-11e7-94c7-9c0fccf6ee87.jpg)

**Comment by iopxiang** [comment]
初始化没问题了，但无法导入证书，每次退出不能保存appid
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1574552/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
@iopxiang  因为java进程中root创建的文件不可读， 误以为文件不存在， 会重新解压。还不清楚为什么会这样

**Comment by XndroidDev** [comment]
@gogo008 日志中看上去 fqrouter和xx-net 运行的都没有问题， 还不清楚为什么会超时

**Comment by lunjielee** [comment]
我用的是magisk

**Comment by 785045633** [comment]
@XndroidDev 授权工具用的是SuperSU 卸载后再装，不给权限可以使用，XX-NET页面第一次进去直接闪退，后面进去XX-NET页面显示请检查浏览器代理设置，但不影响使用。另外再问下手机app怎么使用X-TUNNEL
![tim 20171220162433](https://user-images.githubusercontent.com/34326489/34197965-907bcea8-e5a3-11e7-8f58-17ed3bac21d4.jpg)
![screenshot_20171220-163405](https://user-images.githubusercontent.com/34326489/34198001-b19b22c8-e5a3-11e7-8882-a18d86c7179e.jpg)
[没有授权xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1574730/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
@785045633  见  https://github.com/XndroidDev/Xndroid/issues/14

**Comment by XndroidDev** [comment]
@iopxiang  @lunjielee  @785045633  @gogo008 

给root权限， 卸载后重新下载测试一下这个
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

无论是否正常运行都将日志发过来

**Comment by 785045633** [comment]
root模式致命错误，VPN模式可以进
[VPN-xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1582076/VPN-xndroid-logs.tar.gz)

![_20171222173016](https://user-images.githubusercontent.com/34326489/34292970-cfe94822-e73d-11e7-8713-baac1dd0f713.jpg)

[root-xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1582069/root-xndroid-logs.tar.gz)
![_20171222172756](https://user-images.githubusercontent.com/34326489/34292883-86143d6a-e73d-11e7-91b7-ac6dae91fb02.jpg)

**Comment by XndroidDev** [comment]
@785045633 
感谢反馈， 修复了些问题， 重新编译了
给root权限， 卸载后再重新试试
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

无论是否正常运行都将日志发过来

**Comment by 785045633** [comment]
@XndroidDev  十分感谢 ，root模式可以用了。
![screenshot_20171222-195359](https://user-images.githubusercontent.com/34326489/34297479-59f40998-e753-11e7-9894-0749ecbe1721.jpg)
[Root-xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1582409/Root-xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
@785045633 
网页版youtube 和 google 打不开是因为 XX-Net的 br编码 没有处理好
https://github.com/XX-net/XX-Net/issues/8852#issuecomment-352992343
建议使用firefox， chrome，  
 或尝试将XX-Net更新到 3.8.7（可能仍然会有问题）

另外 fqdns的日志里 发现了 之前没见过的异常， 不清楚是否影响使用

```
Traceback (most recent call last):
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/greenlet.py", line 328, in run
  File "/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/fqdns.py", line 142, in handle
    self.handler(self.sendto, request, address)
  File "/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/fqdns.py", line 243, in __call__
    request = dpkt.dns.DNS(raw_request)
  File "/data/user/0/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/dpkt/dpkt.py", line 72, in __init__
    self.unpack(args[0])
  File "/data/user/0/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/dpkt/dns.py", line 256, in unpack
    q, off = self.unpack_q(buf, off)
  File "/data/user/0/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/dpkt/dns.py", line 227, in unpack_q
    q.name, off = unpack_name(buf, off)
  File "/data/user/0/net.xndroid/files/xndroid_files/python/bin/../lib/python2.7/site-packages/dpkt/dns.py", line 84, in unpack_name
    n = ord(buf[off])
IndexError: string index out of range
<Greenlet at 0xf3733670L: <bound method HandlerDatagramServer.handle of <HandlerDatagramServer at 0xf370be50L fileno=23 address=10.1.2.3:12345>>('@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_', ('192.168.1.107', 37909))> failed with IndexError
```

**Comment by XndroidDev** [comment]
br编码问题已修复, 请更新到最新版
