### ISSUE TITLE
YouTube等网页版正常流畅，但app不能代理

### ISSUE THREAD

**Issue by jamesdengtm** [XndroidDev/Xndroid#3]
小米6 7.1.1。安装后，加了自己id，xxnet升级到3.8.3，其他基本没有设置什么，即可用。YouTube等网页版正常流畅，但app不能代理？是否这样的？

**Comment by XndroidDev** [comment]
app之前没有测试过,似乎是有这个问题.项目刚刚起步,目前先解决兼容性,后续会尝试修复其他app

**Comment by jamesdengtm** [comment]
神器一个！如能解决app代理，我的数十个所谓免费vpn可以退休了。期待，加油！

**Comment by smgzj** [comment]
app里youtube，chrome都可以用
试到现在，只有Instagram无法使用

**Comment by XndroidDev** [comment]
感谢反馈

**Comment by smgzj** [comment]
可怜了，两小时前刚装好时，youtube 720P顺顺畅畅
现在，480p都顿得狗一样

**Comment by iopxiang** [comment]
@smgzj youtube应用应该不可以吧，不要误导开发者哦

**Comment by smgzj** [comment]
@iopxiang
安卓5.1，Moto X 2013，原生youtube app正常使用

**Comment by xiaozijun** [comment]
@XndroidDev  确实，Zuk Z2，App装了Twitter，SnapChat，都是登录的时候出现错误，包括Google Play，打开后首页显示无法连接。我还以为是我个体问题。浏览器上各种网站倒是很顺。

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/14
