### ISSUE TITLE
无论是root模式还是VPN模式均启动失败（Xndroid1.1.4）

### ISSUE THREAD

**Issue by gogo008** [XndroidDev/Xndroid#30]
无论是root模式还是VPN模式均启动失败（Xndroid1.1.4）
手机系统版本：android7.0
已root，已授权
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1570268/xndroid-logs.tar.gz)
![lalpbbcc1ty6m77nbtlnbdm_1075_1746](https://user-images.githubusercontent.com/29323256/34139319-0dce4d22-e4af-11e7-9578-88c7b9a5f456.png)

**Comment by smgzj** [comment]
建议把手机型号报出，安卓的系统真是给各个厂家改得乱七八糟

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/29

@gogo008  卸载后重新安装这个 https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk  无论是否正常运行都将日志发过来

**Comment by 785045633** [comment]
#

**Comment by XndroidDev** [comment]
此问题请转到 https://github.com/XndroidDev/Xndroid/issues/29  交流

**Comment by gogo008** [comment]
用了debug版还是不行（SuperSU，手机：三星note5），日志如下：
[root模式下xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1574051/root.xndroid-logs.tar.gz)
[VPN模式下xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1574052/VPN.xndroid-logs.tar.gz)
![20171220_111916](https://user-images.githubusercontent.com/29323256/34189845-81673874-e578-11e7-8c3a-84ac9ce35864.png)
![screenshot_20171220-111812](https://user-images.githubusercontent.com/29323256/34189846-81a6b422-e578-11e7-9864-f3bf270f33b7.jpg)
