### ISSUE TITLE
请问如何修改xxnet的ip最大数量

### ISSUE THREAD

**Issue by chinaniupai** [XndroidDev/Xndroid#31]
如果把xxnet的最大ip数量修改成300，那么是不是新获取的低延迟ip会替换掉高延迟ip？请问怎么修改？

**Comment by dalton-chiou** [comment]
proxy.ini里有一行：max_good_ip_num =

**Comment by Spring-Falling** [comment]
为什么我的ip数量显示是3900多？？

**Comment by chinaniupai** [comment]
@dalton-chiou 安卓版的找不到这个文件啊，这个文件在哪里？

**Comment by Spring-Falling** [comment]
我没修改，连上就是这样的

牛排大爷 <notifications@github.com> 于 2017年12月20日周三 12:10写道：

**Comment by xxnet** [comment]
​策略里会自动排序的，没有必要改成300
