### ISSUE TITLE
Xndroid 1.15 严重错误 上传日志

### ISSUE THREAD

**Issue by 23Ben** [XndroidDev/Xndroid#33]
请问 Xndroid 
[xndroid-logs.tar.gz](https://github.com/XX-net/XX-Net/files/1583729/xndroid-logs.tar.gz)
的issues 在哪里啊？没找到，只能先上传这里了。知道的麻烦告诉我。或者把帖子移动过去。

**Comment by 23Ben** [comment]
再上传一份 root 模式 debug版 日志。努比亚 Z11  安卓7.1 rr系统  总算不是国内系统的锅了~   我用应用控制器的，以前1.11版本没问题的。 已经加了各项白名单。
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1583736/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
已修复, 稍后将更新

**Comment by XndroidDev** [comment]
更新到 1.1.6

https://github.com/XndroidDev/Xndroid/releases/download/1.1.6/app-release.apk
