### ISSUE TITLE
1.1.5两种模式致命错误（无网络连接）

### ISSUE THREAD

**Issue by madflea** [XndroidDev/Xndroid#34]
- 机型：三星note5（N9200港版），安卓7.0
- 版本：1.1.5
- 错误提示：致命错误 无网络连接，请检查网络设置。
- 日志见附件。

> 
1.1.5之前的版本ROOT模式都是提示xxnet无响应，但是放了一会之后，致命错误下面都显示xxnet都有ip了。求手机fq~
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1583746/xndroid-logs.tar.gz)

**Comment by madflea** [comment]
卡1移动，卡2联通4g上网没问题。求助大神

**Comment by XndroidDev** [comment]
已修复, 稍后将更新

**Comment by madflea** [comment]
@XndroidDev 感谢，辛苦了！

**Comment by XndroidDev** [comment]
更新到 1.1.6

https://github.com/XndroidDev/Xndroid/releases/download/1.1.6/app-release.apk
