### ISSUE TITLE
1.15致命错误

### ISSUE THREAD

**Issue by lu820595769** [XndroidDev/Xndroid#35]
提示无网络连接，请检查网络设置。
安卓版本7.0
日志在附件里
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1583755/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
已修复, 稍后将更新

**Comment by lu820595769** [comment]
@XndroidDev 好的，辛苦了

**Comment by smgzj** [comment]
@XndroidDev,请问还没更吗？

**Comment by XndroidDev** [comment]
更新到 1.1.6

https://github.com/XndroidDev/Xndroid/releases/download/1.1.6/app-release.apk
