### ISSUE TITLE
使用中的几个小问题

### ISSUE THREAD

**Issue by smgzj** [XndroidDev/Xndroid#36]
1.从1.1.4开始，不管是右上角，还是左上角的菜单，选择了“退出”，这应该是正确的退出方式吧？可是退出后不管等多久，再启动，总是会提示”网络错误，无连接“，再退出重启动，才能正常
2.有时会卡在“等待fqrouter反应。。。”，只能强行关闭
3.第一次启动，Teredo经常会显示离线，只能重启

以上问题，1.1.1版本都没有，机器：Moto x 2013，安卓5.1，root
4.待机亮屏后，虽然显示还是连线，但实际已断线，只能关闭重启
但1.1.4后版本，还是有优点的，我最喜欢的是fqrouter里的pick&play
还有悄悄说句，翻墙网速好像比电脑里的XX-net快哦

**Comment by XndroidDev** [comment]
在我的手机上测试是没有出现这些问题的, 请说明你的手机型号和系统版本. 

1. 可能退出时发生了某些异常, 你没有给出日志, 我无法知道原因
2. 没有日志无法知道原因
3. 离线是服务器连不上, 但之后还会再尝试, 1.1.4与1.1.1 都是一样的(不过 1.1.4会尝试更换服务器)
4. 界面里是每五秒刷新teredo状态, 不是绝对实时的. 也有可能是无法连接到fqrouter的管理端口(比如断了wifi 却禁止应用使用移动网络). 1.1.4与1.1.1 无关. 如果没有运行异常, 掉线后还会尝试重新连接, 无需重启

另外说一句, 在我的手机上测试时, pick&play 似乎并没有代理 目标设备的 DNS,  所以有可能会遇到DNS污染的问题
