### ISSUE TITLE
三星s7安卓7.0 启动不了，启动界面出现后直接崩溃掉

### ISSUE THREAD

**Issue by xianshanlai** [XndroidDev/Xndroid#37]
什么原因啊？1.1.6版本

**Comment by XndroidDev** [comment]
有没有日志

**Comment by xianshanlai** [comment]
启动中就奔溃了，导不出日志啊

**Comment by XndroidDev** [comment]
那需要 logcat 日志 , 崩溃时运行到什么阶段
你可以卸载重新安装测试版,在开发者模式里选择调试应用.再次闪退后,在adb shell或其他终端里 执行"logcat -d > /sdcard/logcat.log" 命令,得到logcat日志
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk
