### ISSUE TITLE
好像几个版本里面Google自己的APP也是无法连上的

### ISSUE THREAD

**Issue by xiaozijun** [XndroidDev/Xndroid#38]
Zuk Z2, Xndroid1.16

目前看下来不仅仅是Twitter，Facebook这些，我试过其他APP Snapchat，Pinterest等也都无法使用，Google自己的APP Youtube，GooglePlay，GoogleDrive也都无法使用。比较悲催，因为都是证书原因吧，只能浏览器走天下了。

**Comment by iopxiang** [comment]
Youtube，GooglePlay，GoogleDrive都可以用，要把证书安装为系统证书

**Comment by xiaozijun** [comment]
大概我这个手机的系统证书有毛病，添加进去的时候输入锁屏密码，就进入无限循环模式，小厂安卓，真的无语
