### ISSUE TITLE
无足够IP?下面有显示ip数量呀

### ISSUE THREAD

**Issue by TOBACCOCN** [XndroidDev/Xndroid#39]
![screenshot_2017-12-31-15-53-50-716_net xndroid](https://user-images.githubusercontent.com/26536218/34460219-4bbbba64-ee43-11e7-8a32-0f184c40f3db.png)

  日志已经发到XndroidDev@gmail.com

**Comment by DIY-Missing** [comment]
同问

**Comment by XndroidDev** [comment]
一直都这样吗, 大概teredo服务器有点问题.
teredo地址前半部分是什么,是以2001:0:d911:c0d9 开头吗

**Comment by TOBACCOCN** [comment]
不知道咋回事  白天效果不是很好 teredo地址前半部分是你说的以2001:0:d911:c0d9开头

**Comment by XndroidDev** [comment]
更新到1.1.7试试
