### ISSUE TITLE
测试效果

### ISSUE THREAD

**Issue by LeecGitHub** [XndroidDev/Xndroid#4]
测试环境：三星国行+Android_6.0.1+Xndroid_1.1.1

Tumblr：运行正常；
Pinterest：运行正常；
Facebook：不能连接；
Twitter：不能连接；
Instagram：不能连接；
YouTube等Google App：三星渣渣不root不能安装Google框架、不能测试；

**Comment by jamesdengtm** [comment]
小米6 7.1.1，chrome只有twitter需要用mobile.twitter.com名称连接，其他所有直接可以。用小米内置浏览器就所有都直接可以连接。前贴有说app可以，但我app就一个都不可以。
