### ISSUE TITLE
我自己的appID有密码怎么使用？

### ISSUE THREAD

**Issue by simonfire007** [XndroidDev/Xndroid#40]
电脑上可以在配置文件了填写密码，但xndroid好像没地方填写

**Comment by zidekuls** [comment]
不太清楚，不是都有密码吗？我的是电脑上直接授权给xx-net后，直接输入appid就能用了

**Comment by simonfire007** [comment]
我是部署id的时候设置的有密码，电脑上可以在proxy.ini里填写，手机上我没找到地方。估计是不能使用的，还好我还有不带密码的id可以先用着。

**Comment by XndroidDev** [comment]
这个之前没有考虑.  
应该建议XX-Net 管理页中添加 AppID密码的设置
不过XX-Net似乎并不建议设置密码, 所以建议你重新部署APPID

**Comment by XndroidDev** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids#xx-net%E6%9B%B4%E6%96%B0%E4%B8%8D%E9%9C%80%E8%A6%81%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2%E6%9C%8D%E5%8A%A1%E7%AB%AF%E9%99%A4%E9%9D%9Exx-net%E5%8D%87%E7%BA%A7%E8%AF%B4%E6%98%8E%E4%B8%AD%E6%8F%90%E5%88%B0%E5%8D%87%E7%BA%A7%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%8A%9F%E8%83%BD%E4%BB%A3%E7%A0%81
