### ISSUE TITLE
这个软件只能给浏览器用吗。如何变成全局，给各种app用

### ISSUE THREAD

**Issue by yuyistar** [XndroidDev/Xndroid#42]
说实话。浏览器用的很少，各种app应用才是主要

**Comment by imldf** [comment]
youtube OK啊

**Comment by yuyistar** [comment]
@imldf 手机不用youtube，但是ins，tumblr都不行呀。还有google play也不行

**Comment by imldf** [comment]
有些估計是手機問題啦，不是軟件的問題。軟件不是萬能的。我目前覺得谷歌服務支持最好的國内銷售品牌有：HTC（官方直接提供GMS安裝器，畢竟是Google親兒子系列的製造商）、諾基亞、華爲應該還行。有一些品牌需要第三方的軟件安裝器，比如魅族、小米（感覺不是很安全）。三星排除、VO不説了。一加聽説還行。apple不是Android（新聞説vpn都被下了）。
總的說起來，其實國行手機能滿足我們需求的品牌真的不多。

**Comment by yuyistar** [comment]
@imldf ...?不是手机问题呀。我用其他appvpn都是全局的，各种应用都可以，但是就是不稳定。pc一直用xxnet，所以像转这个。结果发现app不能走他的网络

**Comment by XndroidDev** [comment]
见
https://github.com/XndroidDev/Xndroid/issues/14
https://github.com/XndroidDev/Xndroid/issues/38
