### ISSUE TITLE
夜神模拟器 xndroid崩溃

### ISSUE THREAD

**Issue by pepsicolor** [XndroidDev/Xndroid#45]
夜神模拟器（安卓4.4.2） xndroid崩溃，请求帮助
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1648819/xndroid-logs.tar.gz)

![tim 20180120210303](https://user-images.githubusercontent.com/22813066/35183714-820e2c40-fe25-11e7-89a0-dcac37bc79f5.png)

**Comment by XndroidDev** [comment]
许多所谓的`Android模拟器`其实是虚拟机, 也就是X86架构. 不过你的这个时候有点怪, 同样是native可执行文件, busybox正常运行, python则`Operation not permitted`

**Comment by XndroidDev** [comment]
暂不支持其他架构, 没有相似的反馈
