### ISSUE TITLE
XX-Net升级到3.8.5后 出现崩溃

### ISSUE THREAD

**Issue by xz00311** [XndroidDev/Xndroid#46]
荣耀9  8.0系统  Xndroid V1.1.7, XX-Net 3.8.5 出现崩溃
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1654190/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
具体是什么情况. 日志中发现网络无法连接, 网络配置是否正常

**Comment by XndroidDev** [comment]
未能找到有用的信息, 且无相似反馈
