### ISSUE TITLE
有没有单独实现安卓7.0手机teredo的方法

### ISSUE THREAD

**Issue by xuwanglin** [XndroidDev/Xndroid#47]
单独使用xxnet信用证没问题IPv6有问题，使用nxdroidIPv6没问题信用证导入有问题，xxnet
在127.0.0.1:8085 可以

**Comment by xuwanglin** [comment]
直接下载，nxdroid上不能下载不到

**Comment by xuwanglin** [comment]
或者nxdroid的 ca证书.crt 文件在哪里

**Comment by XndroidDev** [comment]
`/sdcard/XX-Net.crt`
或
`http://127.0.0.1:8085/module/gae_proxy/control/download_cert`

导入证书出了什么问题? 具体一点

**Comment by xuwanglin** [comment]
火狐导入点了没用  原先的XXNET可以导入 只是 没有IPV6 用不了   ， 监控的端口能 改成 127.0.0.1：8085么
我不用共享这个代理    火狐有OMEGA ，或许 改成  127.0.0.1：8085 证书的问题就自然好了，还有真需要teredo的单独的应用  HTTP的vpn没什么用  而且和omega冲突
