### ISSUE TITLE
下载1.17版，可以配置APPID，连接成功，IP数376，延迟288，XX版本3.7.16，可以用浏览器上外网，但FB，TWITTER，YOUTUBE等都不能看到图片和视频。

### ISSUE THREAD

**Issue by sdwxm188** [XndroidDev/Xndroid#48]
1.提交问题前先查看主页readme中是否有描述相关问题
2.再查看issue板块中是否已经提交过相关问题, 有的话就在此issue中提交问题
3.仍然没有相关描述再创建issue, 注意反馈: 手机型号, 系统版本, Xndroid版本, XX-Net版本, 异常提示. 如果有自动导出日志则附上日志, 如果没有自动导出日志, 则重试出现问题时的操作,再次出现问题后点击菜单中的导出日志. 注意上传整个'xndroid-logs.tar.gz', 如果无法上传,则发送到xndroiddev@gmail.com,并附上上述相关信息.

**Comment by sdwxm188** [comment]
还有是以上的APP均不能连接上，只能在浏览器中输入网址，但只有文字

**Comment by XndroidDev** [comment]
浏览器中是否有类似于`智能无图`的设置? 换用其他浏览器试试

**Comment by ydx425** [comment]
确实是。安卓7.1，MIUI9，浏览器里没有问题，App内均无法连接网络。ROOT后一样

**Comment by Lievent5703** [comment]
小米MIUI9一样的问题

**Comment by XndroidDev** [comment]
请仔细查看主页readme!
一些APP不信任GAE的证书
