### ISSUE TITLE
Youtube页面乱码

### ISSUE THREAD

**Issue by toobed** [XndroidDev/Xndroid#5]

**Comment by XndroidDev** [comment]
能否提供更具体的信息,最好给上页面源码

**Comment by szwwluogang** [comment]
XX-Net Status:

sys-platform: aarch64, Linux-3.10.73-perf-g7a5d521-00519-gbbec348-aarch64-with-libc
os-system: Linux
os-version: #1 SMP PREEMPT Mon Sep 18 15:32:24 CST 2017
os-release: 3.10.73-perf-g7a5d521-00519-gbbec348
os-detail: Dist:; Version:; ID:
architecture: 32bit,
browser: Mozilla/5.0 (Linux; Android 5.1.1; NX529J Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/50.0.2661.86 Mobile Safari/537.36
xxnet-version: 3.8.3
python-version: 2.7.2
openssl-version: 0.14 TLSv1_2 h2:no
use-ipv6: force_ipv6
gws-ip-num: total:1067 ipv4:0 ipv6:1041
ipv4-status: OK
ipv6-status: OK
connected-link: new:1 used:0
worker: h1:68 h2:0
scan-ip-thread-num: 6
ip-quality: 286
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by szwwluogang** [comment]
我的也是，youtube页面乱码

**Comment by szwwluogang** [comment]
ߦ���0�78�Yg���9�hd[%���d�,���YE��_��������Wj������~��J���(��njR�~]m��s_�>��3!yP;R��̰�r�{�$H��w�x�)$�K7M M��V�:u���os�o��$��6ߎ��9�V� A֖_m��J�+uk�!��c�/?I B�� Π>�*e��G΍^Xd|��բ^4��I�4�,?����{��ݠ쌜� �Y�ǔ�θ?�w��蝁K_6��z����Y-�LՑ�@�@�@�x���SYg �z�?iw���X�=z�\x�^��(H?�L�աK߿��4����c�di�蝣���jF2=�>�3�EĹ��d� Rv��5QV���֕�DB E����C%8�Ik%��{�s�0�m{$�D�I]I���&s�_@%���|��t�*�%��p�U�^H,��I�=�ީ�G��<( W�=���^��d*/փoX.PT�i>mBM1P �U(����4~W9$�h�K�TqP1�:��Tr7���{�J�G�U�/�F��yF����2�e�#��J_�䩜�d�������ЍE������S'����$Ix���M2]d��/���L��;��:BGN����H|�H��m��m| �F�`�����h�oh(�( ��5��P��l�T�ۘ �g]��x����v$<6����R��%ptမ4�Հ��D�T�B�ET+�k�H��x��7��3My��y�P��4� �C.�(��!K\�֣�4��3}yy�Ȟ���~��T��\�|�4b��[wN�����|�� Uw7�`Ǡ��fO��ky������0d Յ��o��Ycl6W�%���ك���zlF�km��dؿ��LЋ�X��ͦ��CYW��j�ˬ�W��Ӆ�盄�o��iA)��VѬ$�����u�b�;ڷ�����O��|z[���20�H��w��g�ݐ2����_% ��Ħ�j�����Y����S,Ɲ{.��cO۷hQ��V���C�:�5۟ ��5��eW�j�4�pm��<�(�@I�cx��|�:l�&��B!��� ����w���x�Su䱱�X�gf��:������X���m�g�{*��1��j�g��:�2�t�1=a���1���6Ej�+�S�ZRP�>�猲wP�̃������e���6Y�����4曞�=-��Բ�$�J�5MҺ4ɫxg^+���\�$6I�\wc#��Y���j�҃����ޚ�ץD��'"<�Z�M�ɸ�ڭ��-q���f��lۇ��p��Sr�|Cq7��1:���>�c�i��˦���īe�m�m-*�|6f�}�e\,�-w�amݣ嘥Y����ʘ+����8%�z)�ы��H�$S/�څ6�_��q��e�n�;���~�|O"�>dr��U ��H;��g�e[-��I_������^�.��6���i���w+�$��#���ӥ��+q5W��,a��LG�����Sʈf��E��ɽD9�gC.��7Cr,$��s�ӈ����fH���(��΢�HK�L�h�K������z�[�Ԁ%]3���Y�-��QR�t�$���gkZ��5x�\��t����Oz5�µ�-��i,�lCJ.�?!t�g��Z�ڰm�BASFD���>-t��������B�hG�qBa]8�� S\�9.q.�����]�KO�g��X��B���<�C5�� f?A��h����ד���Ga8��������h�&S�J͈����п]@潵�ֆ����Q���xk������> �ǡ(��h�t���F�!����Z8�|�6J齭�ĳN��Rx�u1㼻�����i��?�$f�ۢm���|�/�-��M���#tMG���_���;5�=�0Ò����'UF�i�y܅�U_��$��#���l�P�ژ?����g��̦U5Ѥk�M���ӹp5���irv`��5����,����2M��`1��:�ێn�P��gC���? FiC̒nS���]���ÇQ��$� ��ǳ�cw��Y���\ج�F�B*�<;��\���~�;8�������T��L�ܯ �d�6|�skc� X��]Z����P������Y��)��yi�Ȳ�/��*S;ќ�����@4�į$/����ƗC4����ض��ت�?�G{��Wyi���V���@%}�.'%5u���*�U��Q��4TI~�R6�pL�����]����%Z���`t=��u�cs�Ub)�*��Y�;���jm�kc�2����� K�AՈu���ß���e��0|?�,�G0��WZ�2AɅ��н	�F��n!KZ�~���O-��MG���&�>VԘ$*�4����f)Y��R X�R�T��̪���*N[�!�\"&��)Q���P�ɒ��SB�Y����)�xf�JbH 1���-�XQ�QƆ�,F��/V�z��X���q�K�~h�*�1ʭ�I.G�L�oe"?��$�$(�g�`�ٱ2T�����~�1� �tյ��F�_��W�M3�ǵ����؅vB֭s�2�GŔ�/�a3J�wT�ί�%���$�I=�LQ�� J�����䊟��T�����Ҳ��=�OG��i��Ε4�Q�U*��+�}W�3(�������r�*pS��욙$q�ds�.c��3���*��64���͍2���)�X����B(��s��銺F���+���R��ܹ�2fv�o��Z�B�[�j��j�` ��Ș.����i�Pft@�h~S��Χ�������&eD�m)�t��[ASV�J�2ZrOUV^J�sڤ_�V����8�C4��L��RP���*�WI$�:=P�gOp⡁s�W�S�˵��.gS��'ճPG�X�>09:��i�-����N��9��9eLGr�B�pC4��dC�l͘ɬz�D�0��,���ՃaZ�2a�(0֜I(�Pn�i�� �_`%��W;p�N{�k��W�"ІK�� U�2E�E2�7 6�S��r��򜘁����L���G��ʲ��l~�lC�aЀ�Ph���F�l�ηս��_��w�m=�4|��iug��B� ��6qz�����hL��㘎8e��{�FC:@�ُ�'�#8Ɓ_�ֵA��)R��FA����t��j+�����%�Mh���8��E�Mxb�ѣZ/]GR��Y�I�S��A��ԫd-p��R(�G,�P�mB���z. ��N�&d0�x��I΅; z�	wo7 ���49� Fʤ*��+ڢ$�N�Bsǧ5��%����zOP�o �v#��]i;R(�0x�U�.�R����"X���- �ֿ�l&g��d��) :��T�A@Q�v�ǔ!�6UU����H ���!��`��$��ڒ,W�FxFX�$JWb���/�4^{���,Z�L�����"��v����D���Y ��ʻ@��޸bU��1��s��u�+����J�g��3BQ�PO����1�9p�&���F�wG�u�hO�0��{f+M5����`ђ4w�Wqإ6���IV��0u��`�If>w���֯�&--W�	��%J�ȫ?n��(8εCl�As���#u Զ$҇@u��To�u�:��/��*�P[�)B����6ЕJZm^� L̢�%jSy�>F���Z7^��Y��{S� ���{sP��w=�z����@vov�ʼ���PK�����lcC<����&f�> �ct}��h��v+��϶;�p{���y�������[a����>�>z� +���8�C }�늬�¥O���{�QȾ���(���{H�O���f[]�;Lq��^�jX�2��WeS='�z��c|�2������1=Z��u�?��=_ȷ���{��I?m;ﲝ9mr=�>�����Xo�>�t7Wt�XjZ��9������S?�4�aq���R��jڷ���8OECo��&��뜰�	+[ʚ­'d�(�j�� Xj~��WjcSjP���4N���� 9&D�&q&�^p^}n��:��:�����.T��:SQ�;7��f��nܴ�X%�1MϤQ���M��h%�M02�;��"�QQ�3Ѻ-I� �wˉ���q��z.)fR L Ͽ<��˱�]s��慵i�Og���!�8r,/%f��ZmǴT�ъ�C!��`�X]��q�<hQ�Hf�Ư~�����1��C;��N���

**Comment by xxnet** [comment]
3.8.6 发布，修复br编码问题，请测试

**Comment by XndroidDev** [comment]
嗯,下次更新时更新XX-Net版本
@toobed @szwwluogang  ,在XX-Net中更新到最新版试试

**Comment by XndroidDev** [comment]
br编码问题已修复, 请更新到最新版
