### ISSUE TITLE
华为荣耀长时间运行后Socket无法关闭

### ISSUE THREAD

**Issue by ruey-cn** [XndroidDev/Xndroid#50]
手机型号:华为荣耀，已ROOT
    Xndroid版本:1.16
    XX-Net版本:3.7.16
运行一段时间后，特别是熄灭屏幕很久再开启之后，就不能联网。用netstat看了下，发现xx-net 的8087 的socket端口的RECV-Q值很高，并且都是WAIT_CLOSE状态。netstat的输出可以在附件的hang.txt中查看。
日志manager.txt中报出 **ERROR failed to handle ipv6 packet** 后就再也没有日志了，我在VIVO(未ROOT)上也同样运行，没有这样的问题，一直可以联网。即使报出 **ERROR failed to handle ipv6 packet** 后仍有日志输出。
日志我已上传到[百度网盘](https://pan.baidu.com/s/1jJBfitw)
还请解决下这个问题

**Comment by XndroidDev** [comment]
日志不要发到国内网站上.
Xndroid主页中显示什么信息, XX-Net和fqrouter进程是否仍然在正常运行(ps命令查看)

**Comment by ruey-cn** [comment]
进程还都在运行的。主页显示XX-NET无响应。其他fqrouter都正常的。日志你都下载下来了吗？我删掉网盘上的日志

**Comment by XndroidDev** [comment]
能否打开 XX-Net和 fqrouter的 web管理页, 可能是系统做了什么后台限制

**Comment by ruey-cn** [comment]
XX-NET的管理页打不开，8087和8085端口都没有响应。fqrouter的没有问题，可以打开。
可能就是你分析的系统做了后台限制，每次我熄灭屏幕一段时间再打开就不行了。
但是我连上USB线的时候，熄灭屏幕时间长也还是有反应。

**Comment by ruey-cn** [comment]
分析了一下，发现是xxnet的处理线程再熄灭屏幕重开后出现错误退出了，不能相应请求了。修改了simple_http_server.py中的serve_forever函数原来处理poll的地方，
  def dopoll(self,poller):
        while True: 
            try:
                return poller.poll() 
            except IOError as e: 
                if e.errno != 4: # EINTR:
                    raise
    def serve_forever(self):
        
            while self.running:
              #  events = p.poll(timeout=1)
                 events = self.dopoll(p)
                 for fn, event in events:
                    if fn not in fn_map:
  线程遇到错误不退出，解决了此问题@XndroidDev

**Comment by XndroidDev** [comment]
感谢反馈, 建议将修改提交到XX-Net, @xxnet

**Comment by XndroidDev** [comment]
就是说华为部分手机熄屏后系统会向native 进程发送信号使poll中断?  该信号是否可能会引发其他异常,  
强行忽略`EINTR` , 是否可能影响正常终止XX-Net

**Comment by tradeshark** [comment]
目前本机实验的情况没有影响xxnet的启停和请求的处理。

2018年1月28日 下午7:15，"XndroidDev" <notifications@github.com>写道：

**Comment by xxnet** [comment]
​收到，已经合并到代码中
