### ISSUE TITLE
xndroid稳定，请问是什么teredo？

### ISSUE THREAD

**Issue by jdfq** [XndroidDev/Xndroid#51]
xp开启ipv6隧道的那个工具不稳定，请问怎么开启xndroid的teredo隧道？

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/blob/761cbea52a9213edcfbd6a8578c1727d98760274/fqrouter/manager/teredo.py#L131

**Comment by jdfq** [comment]
谢谢

**Comment by jdfq** [comment]
依然不稳定，看来不是这个问题啊
