### ISSUE TITLE
APPID设置成功，证书也通过，还是不能用

### ISSUE THREAD

**Issue by lily236** [XndroidDev/Xndroid#54]
华为mete9，Android8.0，XX-NET1.1.6
问题描述： 
1.APPID匹配成功，证书也通过，之后界面显示：一切正常，你可自由访问互联网，但是却不能使用。
2.不能更新1.1.7，一更新就显示致命错误，然后进去就自己退出来了
3.附件日志，谢谢
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1684345/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
发过来的只有1.1.6版的日志, 没有找出可能相关的信息

**Comment by lily236** [comment]
是1.1.6的，但是也不能用，为什么？
除了APPID 和 证书，还需要别的什么设置吗？

**Comment by XndroidDev** [comment]
浏览器显示什么信息, 更换浏览器试试(chrome, 内置LightningBrowser).
建议更新到1.1.7后将错误日志发过来

**Comment by lily236** [comment]
更新之后闪退
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1692515/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
里面仍然只有1.1.6版的日志, 看来得要logcat日志

**Comment by lily236** [comment]
这是什么日志，怎么导出

**Comment by XndroidDev** [comment]
有没有显示致命错误和导出日志的提示? 
没有的话就是java异常, 需要logcat日志:

卸载重新安装测试版,在开发者模式里选择调试应用.再次闪退后,在adb shell或其他终端里 执行"logcat -d > /sdcard/logcat.log" 命令,得到logcat日志
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

**Comment by lily236** [comment]
有提示 致命错误和 导出日志提示

**Comment by XndroidDev** [comment]
@lily236 
但发过来的日志没有1.1.7版的
是不是发错了?

**Comment by lily236** [comment]
好像是没更新成1.1.7就直接显示致命错误，导出日志了，每次更新，就直接显示，然后只能退出

**Comment by XndroidDev** [comment]
`没更新成1.1.7`是怎么回事? 下载APK手动安装试试
https://github.com/XndroidDev/Xndroid/releases/download/1.1.7/app-release.apk

**Comment by lily236** [comment]
现在下载1.1.7成功了，显示，一切正常，你可自由访问互联网，但是还是不能进去Google
[xndroid-logs.tar(1).gz](https://github.com/XndroidDev/Xndroid/files/1702209/xndroid-logs.tar.1.gz)

**Comment by XndroidDev** [comment]
浏览器提示什么?

**Comment by lily236** [comment]
浏览器是华为自带的，谷歌也进不去，谷歌商店也进不去

**Comment by lily236** [comment]
大神，closed 是什么意思？ 没办法解决了么？

**Comment by XndroidDev** [comment]
需要更详细的信息, 否则无法判断

**Comment by XndroidDev** [comment]
建议先仔细查看一下 readme和 可能 相关地 issue, 很可能你遇到的问题已经发现过
