### ISSUE TITLE
Android Facebook App无法正常联网(已成功翻墙,可上google)

### ISSUE THREAD

**Issue by qqzwc** [XndroidDev/Xndroid#55]
无论是root模式，还是vpn模式。Android上的Facebook客户端app无法登陆，提示联网异常。
此时关闭xndroid,使用其他vpn,Facebook则可以成功登陆，不知啥原因？

但是确实xndroid已翻墙成功，使用UC浏览器已经可以正常打开YouTube Google

全部使用的安装后默认设置，哪里也没改。软件是最新的1.1.7 xxnet版本3.9.6

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/14

**Comment by KennyQiao** [comment]
> 进入ss软件，编辑代理配置文件，把ipv6路由器的选项关掉就ok了。

果然是这个问题，万分感谢！

**Comment by talkfish8** [comment]
> 进入ss软件，编辑代理配置文件，把ipv6路由器的选项关掉就ok了。

就是这个问题，感谢

**Comment by xuhuiying** [comment]
ss软件是什么呢？

**Comment by qqzwc** [comment]
恩？画风不对啊，这里不是在讨论XX_Net吗？APP上不去是因为不信任xx-net的证书，不过试了导入为系统证书，QQ浏览器还是不信任。
稳定使用无码VPN，挺好的软件

**Comment by a405239606** [comment]
真是，谢谢。
问题得到解决。

**Comment by figthin** [comment]
> 进入ss软件，编辑代理配置文件，把ipv6路由器的选项关掉就ok了。

为啥我关不了？

**Comment by domatos123** [comment]
我也是这个问题，已解决，非常感谢。

**Comment by NERD-k** [comment]
为什么把IPv6关了就可以了？是因为GFW  IPv6解析有问题还是国内IPv6还没普及？

**Comment by kwrong** [comment]
> 为什么把IPv6关了就可以了？是因为GFW IPv6解析有问题还是国内IPv6还没普及？

已经普及了。

**Comment by SweetGirl616** [comment]
我有亮铬Facebook账号，一个登陆了正常使用，另一个APP应用分身，登陆的时候总说网络未打开

**Comment by saber345** [comment]
> 进入ss软件，编辑代理配置文件，把ipv6路由器的选项关掉就ok了。

关掉也不行

**Comment by lnsslimbo** [comment]
打开Apps VPN mode这个配置就好了

**Comment by zengxiaoliang** [comment]
> 打开Apps VPN mode这个配置就好了

大佬，能详细说下 怎么解决的吗

**Comment by Pennyhua95** [comment]
我有两个facebbok账号，华为手机自带fb双开，之前2个账号可以同时登录，在有梯子的情况下。后面我关闭了双开，当我再次开双开，双开的那个程序登不上fb了，总是显示网络l'j错误，

**Comment by 0hotpotman0** [comment]
ss软件打开的时候已经是关闭的，压根不行呀

**Comment by chenyn7** [comment]
可以看下自己的host文件，我的就被改过了

**Comment by MyGoodbye** [comment]
> 我有亮铬Facebook账号，一个登陆了正常使用，另一个APP应用分身，登陆的时候总说网络未打开

你解决了吗？
