### ISSUE TITLE
google, youtube打不开, 其他网站均能正常访问。

### ISSUE THREAD

**Issue by yehuiboy** [XndroidDev/Xndroid#56]
小米6，安卓8.0，开发版8.1.25和最新开发版8.2.1均有标题所述情况，但同为安卓8.0的开发版8.1.18却没有这种情况（即：可以打开谷歌）。由于政策原因没敢向小米反应。特此寻求版主帮助。

关于Xndroid
Xndroid  1.1.7
XX-Net  3.7.16
fqrouter  ULTIMATE
Lightning browser 4.5.1

Xndroid自带Lightning browser浏览器错误提示为：
网页无法打开
位于 https://www.google.com/search?client=lightning&ie=UTF-8&oe=UTF-8&q=1的网页无法加载，因为：
net::ERR_CONTENT_DECODING_FAILED

系统自带浏览器错误提示为：
网页无法工作，因为www.google.com返回的响应无效。（-330）

第三方浏览器（X浏览器）错误提示：
网页无法打开
位于 https://www.google.com/?gws_rd=ssl 的网页无法加载，因为：
net::ERR_CONTENT_DECODING_FAILED

综上，十分期待问题能解决。

**Comment by XndroidDev** [comment]
请仔细查看主页readme, `net::ERR_CONTENT_DECODING_FAILED` 是XX-Net的一个bug, 目前没有完美解决.
建议使用chrome浏览器,或firefox

**Comment by yehuiboy** [comment]
好的，谢谢版主。手机安装chrome浏览器后，可以正常访问网站。

**Comment by XndroidDev** [comment]
br编码问题已修复, 请更新到最新版
