### ISSUE TITLE
没有错误提示还是上不去

### ISSUE THREAD

**Issue by nogi6purple** [XndroidDev/Xndroid#57]
华为P9 android7.0  Xndroid版本1.1.7  XX-net版本3.85  显示可以都OK，但就是上不去
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1691426/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
证书是否正常? 使用内置lightningbrowser是提示什么信息?

**Comment by nogi6purple** [comment]
@XndroidDev 用内置的浏览器提示位于 https://www.google.com/search?client=lightning&ie=UTF-8&oe=UTF-8&q=%E4%B9%83%E6%9C%A8%E5%9D%82 的网页无法加载，因为：

net::ERR_CONTENT_DECODING_FAILED

用我自己手机里的浏览器反而可以上Twitter和Youtube，只是Twitter App依旧没翻出去

**Comment by XndroidDev** [comment]
请仔细查看主页readme

**Comment by nogi6purple** [comment]
@XndroidDev play商店也是属于不信任gae证书的么？

**Comment by XndroidDev** [comment]
据说原生google支持的手机不会有问题, 对于Android7.0 及以上, 可能需要导入为系统证书
