### ISSUE TITLE
/data/data/net.xndroid在哪

### ISSUE THREAD

**Issue by wmh6a4** [XndroidDev/Xndroid#6]
我想把appid复制过去，却找不到，网上说要root才能访问，是真的吗

**Comment by XndroidDev** [comment]
用不着这么麻烦,点击AppId后面的"设置"就可以设置,或者你也可以在XX-Net的"配置"中设置

**Comment by wmh6a4** [comment]
好吧。        htc d10w        夸克，汤不热都能翻
                   Android6.0  
                   Xndroid_1.1.1
