### ISSUE TITLE
xtunnel 的Cloudflare 前端和heroku前端在手机上全都FALSE

### ISSUE THREAD

**Issue by xuwanglin** [XndroidDev/Xndroid#61]
手机的
OpenSSL Version 0.14  TLSv1_2 h2:no

**Comment by xxnet** [comment]
​哪个版本的代码？
cloudflare 依赖 h2， heroku不使用h2
最新版的代码cloudflare的性能有较大提升，消耗资源也少了很多。

**Comment by XndroidDev** [comment]
最新版中内置的pyOpenSSL 不支持http2, 但cloudflare 没有http2支持应该也是可以用的, 可能是其它地方出了问题.
之前试过将pyOpenSSL换成16.0.0版, 但cloudflare 会出现http2连接错误,无法使用.暂时用的旧版pyOpenSSL

**Comment by xxnet** [comment]
​好，回头再研究

**Comment by xuwanglin** [comment]
Heroku front Log
Feb 19 09:12:55.671 - [INFO] SSL use version:TLSv1_2

Feb 19 09:12:55.672 - [INFO] OpenSSL dont't support npn/alpn, no HTTP/2 supported.

Feb 19 09:12:55.822 - [INFO] load ip_list num:134, gws num:134

**Comment by XndroidDev** [comment]
已支持http2
