### ISSUE TITLE
Failed to post notification on channel "null"

### ISSUE THREAD

**Issue by izhangzhihao** [XndroidDev/Xndroid#62]
手机型号:：一加三
系统版本 ：8.1 
Xndroid版本：1.1.7
XX-Net版本：3.10.4

不停地报出这样的日志：

```
Developer warning for package
"net.xndroid"
Failed to post notification on channel "null"
See log for more details
```

![screen](https://user-images.githubusercontent.com/12044174/36539762-d7c21668-1812-11e8-8132-4b74fe9faa2b.png)

日志：[xndroid-logs.tar.gz](https://github.com/XX-net/XX-Net/files/1747926/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
未在日志中发现异常信息, 猜测与 更新通知栏信息 有关, 暂未收到其它类似反馈, 具体情况暂不详.
通知栏相似是否正常(常驻显示XX-Net状态)?  能否提供消息中 `See log for more details` 指的 log (不是xndroid-logs.tar.gz)?

**Comment by izhangzhihao** [comment]
通知栏没有xx net的常驻通知，see log for kore details的log在哪？

**Comment by XndroidDev** [comment]
这个消息不是由Xndroid 显示的, 其它手机都没有显示这样的信息, 我也不清楚

**Comment by izhangzhihao** [comment]
好吧...

**Comment by izhangzhihao** [comment]
似乎需要针对Android Oreo 做一些改动😁

**Comment by XndroidDev** [comment]
Android 8.0 的都可以正常使用, Android8.1 还没有可靠的反馈.  这个消息猜测和你的ROM 或 安装的某个框架之类的有关

**Comment by izhangzhihao** [comment]
系统通知栏确实没有出现xx-net 的通知，其他的应用比如小米系统级推送就可以常驻通知栏...

**Comment by XndroidDev** [comment]
好的 刚刚没有看到 https://stackoverflow.com/questions/45668079/notificationchannel-issue-in-android-o
, 下次更新时会修复

**Comment by XndroidDev** [comment]
@izhangzhihao  
请下载 https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk 测试

**Comment by XndroidDev** [comment]
@722tzz
导入证书的错误可参考: https://github.com/XndroidDev/Xndroid/issues/32 ,你用的 什么授权工具? @izhangzhihao  @722tzz

**Comment by XndroidDev** [comment]
另外顺便测试一下 DEBUG版中内置的LightningBrowser是否能正常使用, 改了targetAPILevel, LightningBrowser有可能会出问题

**Comment by izhangzhihao** [comment]
授权工具：SuperSu 2.82-SR5

**Comment by izhangzhihao** [comment]
装了这个 https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk之后报错
```
Xndroid屡次停止运行
```

**Comment by XndroidDev** [comment]
运行到什么阶段出现的? 有闪退吗

**Comment by izhangzhihao** [comment]
是的闪退了

**Comment by izhangzhihao** [comment]
初始化Python环境结束后就自己退出了

**Comment by XndroidDev** [comment]
能否提供logcat日志? (开发者模式中选择调试应用,闪退后 ,在adb shell 或其他终端中 执行`logcat -d > /sdcard/logcat.log`)

**Comment by XndroidDev** [comment]
@izhangzhihao  请重新下载  https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk 测试安装

**Comment by izhangzhihao** [comment]
通知栏出现了xndroid的常驻通知，警警告没有再出现:smile:

**Comment by izhangzhihao** [comment]
![screenshot_xndroid_20180223-194724](https://user-images.githubusercontent.com/12044174/36592875-7d73c024-18d2-11e8-85ce-227b03b5b083.png)

**Comment by izhangzhihao** [comment]
而chrome中可以正常访问Google

**Comment by XndroidDev** [comment]
这个是XX-Net GAE的br编码问题, 还有待修复. 你看看其他菜单设置界面啥的都正常不

**Comment by izhangzhihao** [comment]
暂时没发现什么问题
