### ISSUE TITLE
不断出现net.xndroid报错,和证书导入错误

### ISSUE THREAD

**Issue by 722tzz** [XndroidDev/Xndroid#63]
手机型号, mi6
系统版本, android 8.0 已root
Xndroid版本, 1.1.7
XX-Net版本, 3.7.16
异常提示. 

下图报错大约每五秒出现一次
![screenshot_2018-02-23-16-09-18-397_net xndroid](https://user-images.githubusercontent.com/12823558/36584539-14f6d4a4-18b5-11e8-9234-75a707f3858a.png)

尝试导入为系统整数时报如下错误
![screenshot_2018-02-23-16-09-19-956_net xndroid](https://user-images.githubusercontent.com/12823558/36584683-b7ef00d2-18b5-11e8-9d06-fcfd3a8b1d56.png)

[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1750876/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
请下载 https://github.com/XndroidDev/Xndroid/issues/62 测试, 
不断弹出消息的问题 转到 https://github.com/XndroidDev/Xndroid/issues/62 交流

**Comment by 722tzz** [comment]
弹出消息问题已解决，谢谢！
