### ISSUE TITLE
Google应用均无法连接服务器。

### ISSUE THREAD

**Issue by Soapere** [XndroidDev/Xndroid#64]
经测试，问题应与xndroid 有关，xndroid 与xx-net均为最新版。

**Comment by XndroidDev** [comment]
https://github.com/XX-net/XX-Net/issues/9719

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/issues/38

**Comment by Soapere** [comment]
谢谢了，原来需要降级。
