### ISSUE TITLE
能否添加teredo+ipv6_hosts或dns的方式进行科学上网的功能

### ISSUE THREAD

**Issue by 821938089** [XndroidDev/Xndroid#65]
APP因为证书问题用不了，直连就不会出现证书问题，稳定性更好。

可参考这个https://github.com/iTXTech/Daedalus

dns要用tcp方式查询，不然还是会污染

**Comment by XndroidDev** [comment]
测试发现, ipv6_hosts实际效果并不太理想. 由于teredo隧道的ipv6并不太稳定, 以及一些网站的ipv6支持并不好, 通过ipv6连接会造成高延时, 甚至无法访问. 而GAE代理 由于有 连接池, 以及google 的ipv6 连接比较稳定, 目前效果相对较好.
你可以尝试下载最新版, 并在fqrouter`代理配置`中开启 `优先ipv6直连`. (测试发现, 访问https://www.google.com, 会跳转到 http, 而被 connection reset, 访问 https://www.google.com.hk 正常. 初次访问由于需要查询AAAA记录, 可能会无法打开)

**Comment by XndroidDev** [comment]
https://github.com/XndroidDev/Xndroid/blob/master/fqrouter/manager/fqsocks/proxies/ipv6_direct.py

**Comment by 821938089** [comment]
以下主要说的就是说换个dns会更好一些。

google的dns解析出来的ip会选择距离你地理位置最近的服务器ip，我这里一般解析出来的都是香港的ip，然而事实上路由却是最远的，延迟相对使用美国ip会高很多（大约高100ms），选择美国的服务器ip访问延迟可以降低，提升访问速度，减少路由数，以及路由环节中的丢包，其实xx-net中ip池里延迟最低的ip就是美国的，我这里大约260ms左右。

推荐美国dns:
ordns.he.net
tserv1.lax1.he.net
对应ipv6地址:
2001:470:20::2
2001:470:0:9d::2

**Comment by XndroidDev** [comment]
有空试试
