### ISSUE TITLE
建议增加goagent连接密码的设置

### ISSUE THREAD

**Issue by tooyangtoonavie** [XndroidDev/Xndroid#67]
pc端可以在文件里设置
manual.ini
[gae]
;添加你自己的appid，多个用竖线 | 分隔
appid = 
;appid密码，无可不填
password =

**Comment by XndroidDev** [comment]
见 https://github.com/XndroidDev/Xndroid/issues/44  https://github.com/XndroidDev/Xndroid/issues/40
更多讨论转到 https://github.com/XndroidDev/Xndroid/issues/44
