### ISSUE TITLE
在小米电视上使用，小米电视4

### ISSUE THREAD

**Issue by xuwanglin** [XndroidDev/Xndroid#68]
小米电视没有root，无法使用开机pin，也就没有办法导入证书，系统安卓6.0,结果一切顺利，在自带的浏览器上能够上YouTube并且能够登录。
但是
但是
但是
只要一打开xndroid，电视的其他应用就全部无法连接网络了，网络检测无法连接本地网关。但是xndroid自带的浏览器却正常使用能够联网。
怎么弄

**Comment by xuwanglin** [comment]
情况补充
当把xndroid的后台清空后，其他的应用才会没有网络，当xndroid打开后恢复，但是速度就最多5兆的带宽。
电视关于本机的网络信息，ipv4本地显示的是26.26.26.1

**Comment by XndroidDev** [comment]
可能是系统的 VPNService 存在BUG

**Comment by XndroidDev** [comment]
`把xndroid的后台清空` 又没终止VPNService, 那网络肯定会出问题呀
