### ISSUE TITLE
关于root模式的两个问题

### ISSUE THREAD

**Issue by WaterFloat** [XndroidDev/Xndroid#69]
1.root 模式，是不是不用导入证书？chrome、和firefox正常使用。
2.root模式下全走代理吗？还是智能选择？

关于1.1.9版，现在可以在x86下使用了。

**Comment by XndroidDev** [comment]
1. root 后会自动导入为系统证书.
2. root模式和vpn模式一样, 默认国内ip和域名直连
3. 用到native库, 理论上不支持x86, 可能是你使用的设备可以模拟arm环境

**Comment by latiaoer** [comment]
root后导入系统证书，Google play.YouTube还是连不上网

**Comment by WaterFloat** [comment]
@XndroidDev 
那root后自动导入的证书如何提取呢？系统证书似乎有点不一样全都是几个数字，以“0“为后缀名的文件

**Comment by XndroidDev** [comment]
证书不存在的时候会自动生成, 每次生成的证书都可能不一样. 点击 XX-Net `CA证书状态` 旁的 `下载` 即可 , 或复制 /sdcard/XX-Net.crt
