### ISSUE TITLE
试用情况

### ISSUE THREAD

**Issue by dalton-chiou** [XndroidDev/Xndroid#7]
xndroid 1.1.1。motorola+android 6.0。清空HOSTS（只剩localhost），在数据网络下测试：

1，内置的LB浏览器可以访问twitter,facetook，无法访问youtube。更无法使用google搜索，无法访问www.google.com/ncr。以上全部是https。LB的代理设置到8087、或不使用代理，都是如此（也就是说LB不设置代理也一样访问facebook等。而有无代理都不通google。）
2，chrome倒可以使用google搜索,能够访问youtube并打开视频。
3，可以访问google play，但无法下载应用。这有点奇怪，因为同样是sn-domains，youtube可以开视频，play却不能下载。

@XndroidDev 情况就是这样。已经很不错了，加油。

还有几点小想法：
1，xndroid退出（从应用内的退出按钮）正常，但lightningbrowser始终保留后台进程，有点不舒服。
2，来自xxnet的通知始终固定在左上角不可移去。可否改一下？
3，可否编译不带LB浏览器的版本？

**Comment by XndroidDev** [comment]
收到

**Comment by XndroidDev** [comment]
@dalton-chiou 我测试的以上网站都可正常访问(google play测不了),你可重试后将日志发过来

1.后续可以尝试退出lightningbrowser
2.通知不可移出(一个是启动VPN时系统会强制显示,另一个是XX-Net的通知,一方面显示信息,更重要的是将xndroid进程置为前台进程,避免被系统强行杀掉),
3.如有广泛需要,lightningbrowser可移除

**Comment by dalton-chiou** [comment]
通知那个不重要（因为如不喜欢，自己可以在android里关闭它）。
还有一个小问题：目前看来是全局模式（fqrouter里暂时调整不了）。那么，当用户访问国内网站时，比如用微信之类，是否也通过代理？（主要是考虑到自己的appid的流量）。

**Comment by XndroidDev** [comment]
从你之前发过来的日志中没有找到任何访问被墙网站的记录。
“（因为如不喜欢，自己可以在android里关闭它）” 不建议关掉它，可能导致进程被系统杀掉
fqrouter会将常见国内IP和域名直连

**Comment by dalton-chiou** [comment]
再发一个日志。这次是分别用LB和chrome访问了google主站。
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1525595/xndroid-logs.tar.gz)

**Comment by dalton-chiou** [comment]
![screenshot_20171204-113205](https://user-images.githubusercontent.com/34107144/33535329-f2faa784-d8e7-11e7-924a-443145827b76.png)
