### ISSUE TITLE
最新版1.1.9，查看内置的XX-Net 卡死

### ISSUE THREAD

**Issue by panpeach** [XndroidDev/Xndroid#70]
安卓6.0，安装了1.1.9版本(集成XX-Net 3.10.4)，点击设置-XX-Net，查看里面任何一项卡顿很久，
当能操作后，在系统配置-模块管理里关闭smart router后，立即就能流畅查看配置XX-Net各项。
（上个1.1.7版本，升级XX-Net 3.8.5版本，没上述问题）

**Comment by XndroidDev** [comment]
smart router 不应该默认是关闭的吗, 目前手机上smart router使用不是特别完美, 直接使用GAE 或 X-Tunnel 或 其它代理就好

**Comment by panpeach** [comment]
更新后第一次启动，smart router默认开启的，卡了很久才能进入系统设置里，关闭smart router后既能流畅操作XX-Net各项设置。

**Comment by XndroidDev** [comment]
未发现新版本有此问题

**Comment by AnyWAT** [comment]
貌似1.2.2安装后默认系统代理 smart router （1.1.9是PAC？）
