### ISSUE TITLE
1.1.9在红米note5a VPN模式必须手动断开

### ISSUE THREAD

**Issue by jdfq** [XndroidDev/Xndroid#73]
安卓7吧，没有root。正常退出后，VPN依然在。然后不手动断开VPN，就不能再正常启动

**Comment by jackzhum** [comment]
我也是同样情况，在APP里点退出VPN会驻留，然后什么网络都打不开，必须得把进程结束掉才可以。
Android 8.0

**Comment by XndroidDev** [comment]
@jdfq @jackzhum  
能否在问题出现后导出日志并上传?

**Comment by leothronton** [comment]
小米MIX2也有这个问题。虽然正常退出，但在VPN设置中Xndroid仍然显示已连接。如果关闭VPN会自动启动Xndroid。来回跳转。只能关机重启才行。系统是MIUI9.5稳定版。

**Comment by XndroidDev** [comment]
@leothronton  我这边没有相同的机型来测试, 要找到原因需要 Xndroid日志 和 系统的Logcat日志

**Comment by caofengzi** [comment]
昨天俺頭一次使用xndroid也是正常退出後vpn需要手動停止，手機是新諾基亞6二代，系統是8.1.1接近原生系統，另外內置存儲裡面怎麼沒有程序目錄？

**Comment by jdfq** [comment]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/2188343/xndroid-logs.tar.gz)
我已经用最新稳定版了，问题依旧。

**Comment by fredericky123** [comment]
@jdfq 请问如何能实现手动断开vpn，我在使用后只能通过重启的方式才能正常访问网络，重启之后vpn肯定断开了

**Comment by XndroidDev** [comment]
已修复, 更新到最新版
https://github.com/XndroidDev/Xndroid/releases/download/1.2.4/app-release.apk
