### ISSUE TITLE
关于Google Play Store不能使用问题

### ISSUE THREAD

**Issue by jackzhum** [XndroidDev/Xndroid#74]
状态已连接，其它App也没问题，只有Google应用商店连接不上，显示"[DF-DFERH-01]"的错误，查了下相关的资料，发现是域名services.googleapis.cn被解析到了上海的服务器上。不知道有没有办法解决这个问题。

**Comment by shanligang1017** [comment]
我也是同样问题，其他谷歌网页都可以用，谷歌商店不行

**Comment by smqsrgswc** [comment]
我的也一样 谷歌应用商店不能访问  但其它谷歌应用可以  root了也不行 希望有办法改进

**Comment by shanligang1017** [comment]
发现APP的都不行，网页的都可以，估计证书什么之类的影响吧

**Comment by XndroidDev** [comment]
请仔细查看readme
