### ISSUE TITLE
进入Xndroid后X-Tunnel无法正常登陆

### ISSUE THREAD

**Issue by AlexanderShang** [XndroidDev/Xndroid#75]
在进入Xndroid后，切换进XX-Net后，无法正常登陆X-Tunnel，如何解决？ @XndroidDev

**Comment by XndroidDev** [comment]
无法正常登陆X-Tunnel,具体是什么情况？显示什么提示？

**Comment by AlexanderShang** [comment]
Mar 18 19:20:35.363 - [DEBUG] session not running, try login..

Mar 18 19:20:37.900 - [WARNING] front retry center.xx-net.net/login

Mar 18 19:20:40.838 - [WARNING] front retry center.xx-net.net/login

Mar 18 19:20:44.677 - [WARNING] front retry center.xx-net.net/login

Mar 18 19:20:48.145 - [WARNING] front retry center.xx-net.net/login

Mar 18 19:20:51.955 - [WARNING] front retry center.xx-net.net/login

Mar 18 19:20:54.806 - [WARNING] front retry center.xx-net.net/login

Mar 18 19:20:58.702 - [WARNING] front retry center.xx-net.net/login

**Comment by AlexanderShang** [comment]
@XndroidDev

**Comment by AlexanderShang** [comment]
@XndroidDev

**Comment by AlexanderShang** [comment]
Mar 22 16:00:40.539 - [DEBUG] session not running, try login..

Mar 22 16:00:42.989 - [WARNING] front retry center.xx-net.net/login

Mar 22 16:00:46.029 - [WARNING] front retry center.xx-net.net/login

Mar 22 16:00:51.952 - [WARNING] front retry center.xx-net.net/login

Mar 22 16:00:54.248 - [WARNING] front retry center.xx-net.net/login

**Comment by AlexanderShang** [comment]
在重装并更新内部XX-Net后仍然无法正常登录 @XndroidDev
