### ISSUE TITLE
两个安卓盒子都不成功

### ISSUE THREAD

**Issue by account271828** [XndroidDev/Xndroid#76]
第一个盒子，芒果Q，安卓4.4 。启动时卡在 启动vpn服务，请确认。没有确认按钮。
第二个天猫魔盒1s+，ipV6总failed。  IP扫描日志是空白的，好像不扫描。
可能都是系统原因？系统版本太低了？

**Comment by buhtig314** [comment]
无法添加vpn ，vpn列表里是空的。

**Comment by XndroidDev** [comment]
请上传日志
