### ISSUE TITLE
[调查]是否希望移除LightningBrowser

### ISSUE THREAD

**Issue by XndroidDev** [XndroidDev/Xndroid#8]
LightningBrowser为早期未加入fqrouter的情况下,为方便使用加入.现已集成fqrouter,正常情况下无需LightningBrowser.是否希望移除LightningBrowser?

**Comment by iopxiang** [comment]
希望移除，减小体积，减少后台

**Comment by xiaozijun** [comment]
我觉得可以移除，目前走VPN，内置浏览器意义不大。

**Comment by XndroidDev** [comment]
刚刚有反馈Android 7.x不支持自导入的证书，使用Android 7.0的朋友测试一下
[https://github.com/XndroidDev/Xndroid/issues/9](https://github.com/XndroidDev/Xndroid/issues/9)

**Comment by V4n1sh** [comment]
一般来讲，有需要使用Xndroid需求的人应该不会用这个浏览器吧？我个人觉得可以去掉，不过如果有好的实现方式也许能做成类似XX-Net一样关闭特定功能（比如关闭X-tunnel或GAE）？

**Comment by wankuizhuankan** [comment]
用内置浏览器有速度，用其他浏览器速度巨慢

**Comment by Jarvanh** [comment]
我觉得移除比较好，或者做成插件。

**Comment by iopxiang** [comment]
@XndroidDev android 7.0 可以自动导入证书

**Comment by wankuizhuankan** [comment]
搞错了，是qq浏览器开了加速造成的问题

**Comment by wmh6a4** [comment]
移除，这东西没用

**Comment by theratlesnake** [comment]
还是不要移除吧，把浏览器在关闭app后还会驻在后台这个解决了就好，反正也就是14M也不大，留着还可以多一个浏览器使用，多好啊。

**Comment by godbin1990** [comment]
荣耀8 安卓7.0，手机已root，CA证书导入后仍无法访问https，将ca证书移至etc/security/cacerts下仍无法正常访问https，不知道还有没有救？感谢如此优秀的项目。

**Comment by xxnet** [comment]
​能否做成应用内下载？

默认不包含LightningBrowser，少数情况下需要的，可以方便的加载（安装）进来。

**Comment by XndroidDev** [comment]
由于Android 7.x的手机默认不信任用户导入的证书，因此LightningBrowser暂时保留
https://github.com/XndroidDev/Xndroid/issues/9
不过LightningBrowser本来就是独立应用，后期可以独立出来，自行安装就好
