### ISSUE TITLE
一直搜索不到可用IP,PC端XX-NET正常

### ISSUE THREAD

**Issue by chen-xinjun** [XndroidDev/Xndroid#81]
手机型号:nexus 6P
系统版本:android 8.1.0
Xndroid版本:1.1.9
XX-Net版本:3.10.4
![image](https://user-images.githubusercontent.com/12838587/37697959-16513d6a-2d1b-11e8-9a31-77bb348504ba.png)
![image](https://user-images.githubusercontent.com/12838587/37698035-8c69a992-2d1b-11e8-93dd-d881c3cd1ba1.png)

**Comment by XndroidDev** [comment]
请上传日志

**Comment by chen-xinjun** [comment]
哪种日志?崩溃日志还是扫描日志?

**Comment by chen-xinjun** [comment]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1843941/xndroid-logs.tar.gz)
这个日志是刚导出的. 
目前的状态和我上次描述的已经发生改变.
目前我从PC端导出IP ,手机端导入IP .
但是依然提示"连接尚未建立"
连接池中没有能够建立连接的IP

**Comment by XndroidDev** [comment]
Teredo状态显示什么？

**Comment by chen-xinjun** [comment]
状态正常，明天上图，手机不在身边

**Comment by XndroidDev** [comment]
fqrouter的配置是否正确? 清除应用数据试试

**Comment by chen-xinjun** [comment]
清除应用数据后,可以正常使用了.
