### ISSUE TITLE
小米盒子增强版（andriod 4.2.2）无法启动

### ISSUE THREAD

**Issue by shanzigang** [XndroidDev/Xndroid#83]
在zidoo x9s（andriod 6.0 已root0）上可以完美运行，但在小米盒子增强版（andriod 4.2.2）版本上，提示 xx-net无法启动。是否不兼容低版本的andriod?

**Comment by XndroidDev** [comment]
请上传日志,
参考 https://github.com/XndroidDev/Xndroid/issues/53

**Comment by XndroidDev** [comment]
转到 #53
