### ISSUE TITLE
提示互联网正常但是无法科学上网

### ISSUE THREAD

**Issue by klcb2010** [XndroidDev/Xndroid#84]
[root模式提示IPv6暂时不可用，VPN模式提示网络正常，可以自由访问互联网。但是任何程序都无法访问墙外链接。百度等国内app没问题，日志发送到油箱xndroiddev@gmail.com

**Comment by XndroidDev** [comment]
root模式下teredo 状态是否正常? 手机机型? 系统版本?

**Comment by XndroidDev** [comment]
2018-03-26 18:25:54,187 ERROR qualify procedure fail once
Traceback (most recent call last):
  File
"/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/teredo.py",
line 398, in qualify_retry
    return self.qualify(dst_ip)
  File
"/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/teredo.py",
line 381, in qualify
    self.send_qualify(dst_ip)
  File
"/data/data/net.xndroid/files/xndroid_files/fqrouter/manager/teredo.py",
line 377, in send_qualify
    self.teredo_sock.sendto(self.rs_packet, (dst_ip, teredo_port))
  File
"/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/socket.py",
line 474, in sendto
error: [Errno 1] Operation not permitted

**Comment by klcb2010** [comment]
@XndroidDev  teredo离线   Sony xzp Android8.0. 目前升级xxnet到3.11.7后 VPN一切正常，root模式仍不可用！

**Comment by XndroidDev** [comment]
分别使用root模式, 和vpn模式后 将日志发过来

**Comment by klcb2010** [comment]
很奇怪  这次换到vpn模式  所有程序联网正常了  辛苦对比一下
[xndroid-vpn模式成功联网日志logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1879782/xndroid-vpn.logs.tar.gz)
