### ISSUE TITLE
Teredo连接正常 但XX-NET ipv6 fail 

### ISSUE THREAD

**Issue by yutianzeabc** [XndroidDev/Xndroid#86]
华为 G7-TL00 系统EMUI 3.0 (android 4.4.4) Xndroid 1.1.9 XX-NET内置版本
Xndroid 初始化过程一切顺利无报错，Teredo连接正常也获取到了ipv6地址，但XX-NET始终ipv6 fail,扫描不到ip，已更换多种网络环境尝试问题依旧。

[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1856282/xndroid-logs.tar.gz)

**Comment by XndroidDev** [comment]
参考 https://github.com/XndroidDev/Xndroid/issues/23
运行一段时间后提供一下XX-Net日志
