### ISSUE TITLE
fqrouter，如何指定特定的网站或APP走代理？

### ISSUE THREAD

**Issue by fuhuajiao** [XndroidDev/Xndroid#87]
outlook邮箱的APP，直连被墙了，用VPN没问题，Xndroid连不上，估计在fqrouter白名单内，如何设定它走GAE啊？如果像SwitchyOmega一样，就方便使用。

**Comment by XndroidDev** [comment]
outlook 怎么也被墙了😌, 如果你root了,可以手动修改:
/data/data/net.xndroid/files/xndroid_file/fqrouter/manager/china_domains.txt
