### ISSUE TITLE
能够显示一切正常，但是无法打开谷歌

### ISSUE THREAD

**Issue by q995051** [XndroidDev/Xndroid#88]
我的是一加5，安卓8.1系统，显示一切正常，你可自由访问互联网。
但是实际，我打开后，google是一些乱码。甚至有时候乱码都没有。
![screenshot_20180330-102544](https://user-images.githubusercontent.com/37919499/38122139-eb19d91c-3405-11e8-8a1b-0c25880d729b.png)

**Comment by xxnet** [comment]
已知bug，​请升级3.11.7

**Comment by q995051** [comment]
感谢，正在升级中。

**Comment by ijustknow** [comment]
在软件界面中选about,版本是3.10.4,检查更新却说是最新版本？

**Comment by q995051** [comment]
不可能都没有翻出去吧，检测不到。

**Comment by AnyWAT** [comment]
@ijustknow 主菜单——XX-Net——（系统）配置——版本——手动管理——全部已发布版本——想用哪个选哪个，下载后会自动安装
