### ISSUE TITLE
VPN模式下浏览器和国内app网络正常，但是国外app无网络连接

### ISSUE THREAD

**Issue by klcb2010** [XndroidDev/Xndroid#90]
Sony xzp Android8.0，目前升级xxnet到3.11.7，teredo正常。VPN模式下浏览器和国内app网络正常，但是国外app如xdalab、apkpure无网络连接。日志已经传到开发者邮箱

**Comment by XndroidDev** [comment]
ROOT模式是否正常?

**Comment by klcb2010** [comment]
正如上次反馈的，root模式提示IPv6未连接！@XndroidDev

**Comment by XndroidDev** [comment]
更新到最新版试试

**Comment by klcb2010** [comment]
最新版不就是1.1.9？

**Comment by XndroidDev** [comment]
https://raw.githubusercontent.com/XndroidDev/Xndroid-update/master/update/app-debug.apk

**Comment by klcb2010** [comment]
更新到1.1.10还是一样

**Comment by XndroidDev** [comment]
启用一段时间后再次导出日志, 上传. 尽量传到github

**Comment by klcb2010** [comment]
[xndroid-logs.tar.gz](https://github.com/XndroidDev/Xndroid/files/1879709/xndroid-logs.tar.gz)
测试运行 XDA Labs 无法联网的日志
