### ISSUE TITLE
请教如何设置Telegram通过Xndriod科学上网？

### ISSUE THREAD

**Issue by fransewoo** [XndroidDev/Xndroid#91]
打开Xndriod后Telegram老是显示正在连接，也在Telegram设置过代理127.0.0.1:8087，但是就是无法连接上。

**Comment by AnyWAT** [comment]
参考：https://github.com/XndroidDev/Xndroid/issues/53 底楼，或许有助？

**Comment by XndroidDev** [comment]
证书原因
