### ISSUE TITLE
使用GAE PROXY正常，但是没有X-tunnel模块，怎么登录？

### ISSUE THREAD

**Issue by Wenn3** [XndroidDev/Xndroid#92]
Xndroid中 内置XX-net版本为3.11.7，是否可以手动更新此版本？

**Comment by Wenn3** [comment]
Xndroid为1.1.10版本

**Comment by AnyWAT** [comment]
稳定版1.1.9 (XX 3.10.4)主菜单——XX-Net——（系统）配置——版本——手动管理——全部已发布版本——想用哪个选哪个，下载后会自动安装
没有X-tunnel模块：稳定版1.1.9 (XX 3.10.4)主菜单——XX-Net——（系统）配置——模块管理——启用 X-Tunnel——ON

**Comment by Wenn3** [comment]
解决了，谢谢 可以使用x-tunnel了
