### ISSUE TITLE
谷歌网盘提示错误

### ISSUE THREAD

**Issue by klcb2010** [XndroidDev/Xndroid#94]
下载文件的时候 提示错误  VPN 模式  下
600:gae_exception:'600:fetch gae fail' https://doc-04-bk-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/n2rjisssv3hak9tuov1n0m6mksjfu445/1523311200000/01181908603749165722/*/1hpn9Ka6fPiIjlB_DFQclyY67XIX8DuXL?e=downloadgae_exception:'600:fetch gae fail' https://doc-04-bk-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/n2rjisssv3hak9tuov1n0m6mksjfu445/1523311200000/01181908603749165722/*/1hpn9Ka6fPiIjlB_DFQclyY67XIX8DuXL?e=downloadgae_exception:'600:fetch gae fail' https://doc-04-bk-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/n2rjisssv3hak9tuov1n0m6mksjfu445/1523311200000/01181908603749165722/*/1hpn9Ka6fPiIjlB_DFQclyY67XIX8DuXL?e=download

**Comment by AnyWAT** [comment]
貌似代理速度的锅？ https://github.com/XndroidDev/Xndroid/issues/93
