### ISSUE TITLE
未root下使用xndroid持续产生警告

### ISSUE THREAD

**Issue by wongkabond** [XndroidDev/Xndroid#95]
1.提交问题前先查看主页readme中是否有描述相关问题
2.再查看issue板块中是否已经提交过相关问题, 有的话就在此issue中提交问题
3.仍然没有相关描述再创建issue, 注意反馈: 手机型号, 系统版本, Xndroid版本, XX-Net版本, 异常提示. 如果有自动导出日志则附上日志, 如果没有自动导出日志, 则重试出现问题时的操作,再次出现问题后点击菜单中的导出日志. 注意上传整个'xndroid-logs.tar.gz', 如果无法上传,则发送到xndroiddev@gmail.com,并附上上述相关信息.
4.日志和相关信息不要保存在国内网站上. 日志尽量传到issue中, 方便后续查看, 实在无法上传则通过邮箱发送.

**Comment by wongkabond** [comment]
机型：oneplus A5000 
系统：基于Android 8.0.0（H2OS 5.0.2） 
XX-Net 版本： 3.11.7 
xndroid版本： 1.1.6 
日志及异常提示由邮箱发送

**Comment by wongkabond** [comment]
thank you

**Comment by XndroidDev** [comment]
Android8.0 兼容性问题, 已经修复, 将Xndroid更新到最新版
