### ISSUE TITLE
用apk editor修改xndroid安装包到xx-net 1.119是否会导致证书问题？

### ISSUE THREAD

**Issue by Soapere** [XndroidDev/Xndroid#97]
如题，反正我修改后就有证书问题。如果是真的话，那么证书在哪？或者是不是xx-net 1.119本身有问题？

**Comment by AnyWAT** [comment]
没太明白楼主的意思😜
证书保存在：data/data/net.xndroid/files/xndroid_files/xxnet/data/gae_proxy/
https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA Android手动导入证书

**Comment by AnyWAT** [comment]
貌似稳定版1.1.9（XX3.10.4）（没有用户操作的原因）安装的结果，data/data/net.xndroid/files/xndroid_files/xxnet/code 下有目录3.10.4及 default，目录不同的两完全一致3.10.4版？
🤣“保留的旧版本数”非0，更新XX-Net（如3.11.7）后保存不了旧版本3.10.4，只剩目录3.11.7及 default，目录不同的两完全一致3.11.7版。
更改“最大扫描线程数”后貌似经常回到默认值，又见比自设定值大，退出检查设置文件发现保存的就是被随机改大的那个数字😂
貌似IP上限数也不受自定义1000的控制中（已手动退回到3.10.4）
用回3.8.4（没有“智能路由的最高版本”）已受控制🤣
