### ISSUE TITLE
不慎将以root模式运行的Xndroid人工强制关闭后，手机wifi和移动数据均无法上网，请问如何修复，谢谢！

### ISSUE THREAD

**Issue by yyt3213** [XndroidDev/Xndroid#98]
不慎将以root模式运行的Xndroid人工强制关闭后，手机wifi和移动数据均无法上网，请问如何修复，谢谢！实在不想刷机重装，求打救。

**Comment by AnyWAT** [comment]
😜程序启动中的提示：
以root模式启动，请勿强制退出，如果造成网络异常，请重新以root模式启动并正常退出，或重启设备。

**Comment by yyt3213** [comment]
AnyWAT您好，这条后来我也看到了。现在的情况是我以root模式或vpn模式启动后会弹出Fatalerror的对话框，说网络无法连接，请检查网络设置。对话框下面只有一个退出选项。退出后重启机子，故障依旧，wifi和移动数据都上不了网。

**Comment by AnyWAT** [comment]
root 了还不好说，点击 data\app\net.xndroid-?.apk 重新安装下？

**Comment by AnyWAT** [comment]
网络无法连接，请检查网络设置：。。。断网再联网？

**Comment by yyt3213** [comment]
已重装过xndroid，故障依旧。现在情况是连wifi或移动数据后信号显示都正常，但就是访问不了网络。怀疑是哪个跟网络连接相关系统文件被修改了没还原导致上不了网。另外短信和电话功能也是正常的。唯独wifi和移动数据都上不了网。

**Comment by AnyWAT** [comment]
貌似卸载了重装，证书已无效，需重新加载。。。

**Comment by yyt3213** [comment]
刚去系统设置里看了一下，发现里面有XX-NET的GoAgent证书，处在启用状态。你是指这个证书吗？

**Comment by yyt3213** [comment]
另外尝试了卸载Xndroid后并重启手机，故障依旧

**Comment by AnyWAT** [comment]
启用再禁用飞行模式？
备份用户数据，重置手机？

**Comment by yyt3213** [comment]
飞行模式切换过不管用。
重置手机还没试，因为实在不想重装，有太多软件插件什么的要弄，还是想尽力抢救。

**Comment by yyt3213** [comment]
用netstat查看过，一个端口都没有，一片空白。

**Comment by AnyWAT** [comment]
怎么玩？来试试好对比

**Comment by AnyWAT** [comment]
卸载、清理、安装？

**Comment by SeaHOH** [comment]
应该是 iptables 被修改了吧，谷歌`重置 iptables`。

**Comment by AnyWAT** [comment]
🤣不会是离奇错误：PAC代理调整到了GAE（全局）代理（电脑上容易出现），GAE正常前需要也无法联网，GAE不正常，整个网络不正常。。。
检查 config.yaml 内容 proxy: pac

**Comment by SeaHOH** [comment]
搞不明白，只能 @XndroidDev 了。

**Comment by XndroidDev** [comment]
@yyt3213 
iptables规则重启后失效, 如果重启后仍然无法联网, 那大概和Xndroid无关了

**Comment by SeaHOH** [comment]
会不会是热重启？尝试关机完全重启？

**Comment by XndroidDev** [comment]
长按电源键(10秒以上)强制关机

**Comment by yyt3213** [comment]
@XndroidDev 有尝试重启或关机重启，也给予了root权限。Xndroid启动过程中会弹出fatalerror对话框，然后只能按退出键。不知这过程到底有没有清理iptables规则。另我已手动重置过iptables，故障依旧。怀疑Xndroid除了iptables外还改动了一些系统文件实现全局代理？

**Comment by XndroidDev** [comment]
手机电池能拔掉吗, 怀疑还是没有完全重启, 试试终端下输入`reboot`命令, 或者强制关机

**Comment by yyt3213** [comment]
问题原因终于找到了！用catlog仔细看了一下，发现在打开wifi后有几条关于iptables的报错纪录，大意是说无法执行iptables的 -w这个选项，google了一下这情况是由于这个iptables版本太旧。这时候想起来之前出现网络故障后稀里糊涂地更换了一个iptables文件，没想到换的是一个旧版本。去别的机子上拷贝一个新版本的iptables到系统目录，故障解除。这次的教训是Catlog是个好东西，出现这类问题要先从系统log着手。再次感谢各位的帮助，也是由于大家多次强调iptables的问题最后我才能找到原因，感谢感谢！

**Comment by SeaHOH** [comment]
我都快想要叫你放弃啦 :sweat_smile:

**Comment by yyt3213** [comment]
@SeaHOH 😁我之前也确实准备刷机了，刷机包都找好了，万幸。

**Comment by yyt3213** [comment]
@SeaHOH 😁我之前也确实准备刷机了，刷机包都找好了，万幸。
